// https://github.com/dkxce/NES/tree/main/GamesByAlphabet.EN/0..9


x= "https://drive.google.com/thumbnail?id="
agregarJuegos([
    { system: "nes", img: x+ "1jKRthY7Cx356aVCMyOjqieDV5qj-xnPt", title: "DETH COMPLEX 2", src: "dethcomplex2.nes" },
    { system: "nes", img: x+ "10Qzz4bcGnNBO71gSqtnRcWEpAKVNcHBx", title: "MAGICAL DUNGEON 3D", src: "magicaldungeon3d.nes" },
    { system: "nes", img: x+ "1obaks5fuTIq311mTSgHdgAH3xVQOwhSF", title: "PONG TMNT TRILOGY", src: "pongtmnttrilogy.nes" },
    
    
    
    { system: "nes", img: x+ "16iGfq1kYXCB6b0wyIb1MYIrRJ6A13cRT", title: "10 YARD FIGHT"  src: "https://github.com/dkxce/NES/raw/refs/heads/main/GamesByAlphabet.EN/0..9/10-Yard%20Fight%20(J).nes" },
    { system: "nes", img: x+ "16iGfq1kYXCB6b0wyIb1MYIrRJ6A13cRT", title: "1943" },
    { system: "nes", img: x+ "1lSO7bxZ685Fgyi9BhmOlt9qR-S9jhJjV", title: "A NIGHTMARE ON ELM STREET" },
    { system: "nes", img: x+ "1dDPPFRivP3csw37c6jzX0Mw7vNQHoOfJ", title: "ACTION IN NEW YORK" },
    { system: "nes", img: x+ "1628R0M-PjbGnBeBcDBgHfs7AhDFIyGfN", title: "ADVENTURE ISLAND" },
    { system: "nes", img: x+ "10TQOV60P_yd3X-0r1EBb3yVt_Taxa36a", title: "ADVENTURE ISLAND 2" },
    { system: "nes", img: x+ "1sjpQPRhl6uR91FyBftQiX9-adQHTC38j", title: "ADVENTURE ISLAND 3" },
    { system: "nes", img: x+ "", title: "ADVENTURES OF DINO RIKI" },
    { system: "nes", img: x+ "", title: "ADVENTURES OF LOLO" },
    { system: "nes", img: x+ "", title: "ADVENTURES OF LOLO 2" },
    { system: "nes", img: x+ "", title: "ADVENTURES OF LOLO 3" },
    { system: "nes", img: x+ "", title: "ADVENTURES OF TOM SAWYER" },
    { system: "nes", img: x+ "", title: "AIR FORTRES" },
    { system: "nes", img: x+ "", title: "ALADDIN" },
    { system: "nes", img: x+ "", title: "ALFRED CHICKEN" },
    { system: "nes", img: x+ "", title: "ALIEN 3" },
    { system: "nes", img: x+ "", title: "ALIEN SYNDROME" },
    { system: "nes", img: x+ "", title: "ALPHA MISSION" },
    { system: "nes", img: x+ "", title: "AMAGON" },
    { system: "nes", img: x+ "", title: "ARKANOID" },
    { system: "nes", img: x+ "", title: "ARKISTA\'S RING" },
    { system: "nes", img: x+ "", title: "ASTERIX" },
    { system: "nes", img: x+ "", title: "ASTYANAX" },
    { system: "nes", img: x+ "", title: "ATHENA" },
    { system: "nes", img: x+ "", title: "ATTACK OF THE KILLER TOMATOES" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    
    { system: "nes", img: x+ "1IIZwRY1HuBplQ20KewH3gsywOjW8EWnu", title: "DRAGON STRIKE" },
    
    
    
    
    
    
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    { system: "nes", img: x+ "", title: "" },
    
    
    
    
    
agregarJuegos([
    { title: "10-Yard Fight", system: "nes", img: "", src: "roms/nes/10yard.nes" },
    { title: "1942", system: "nes", img: "", src: "roms/nes/1942.nes" },
    { title: "1943: The Battle of Midway", system: "nes", img: "", src: "roms/nes/1943.nes" },
    { title: "1943 Kai", system: "nes", img: "", src: "roms/nes/1943kai.nes" },
    { title: "720°", system: "nes", img: "", src: "roms/nes/720.nes" },
    { title: "8 Eyes", system: "nes", img: "", src: "roms/nes/8eyes.nes" },
    { title: "A Boy and His Blob: Trouble on Blobolonia", system: "nes", img: "", src: "roms/nes/blob.nes" },
    { title: "Action 52", system: "nes", img: "", src: "roms/nes/action52.nes" },
    { title: "Adventure Island", system: "nes", img: "", src: "roms/nes/advisland.nes" },
    { title: "Adventure Island II", system: "nes", img: "", src: "roms/nes/advisland2.nes" },
    { title: "Adventure Island III", system: "nes", img: "", src: "roms/nes/advisland3.nes" },
    { title: "Adventure Island IV", system: "nes", img: "", src: "roms/nes/advisland4.nes" },
    { title: "Adventures in the Magic Kingdom", system: "nes", img: "", src: "roms/nes/magickingdom.nes" },
    { title: "Adventures of Lolo", system: "nes", img: "", src: "roms/nes/lolo.nes" },
    { title: "Adventures of Lolo 2", system: "nes", img: "", src: "roms/nes/lolo2.nes" },
    { title: "Adventures of Lolo 3", system: "nes", img: "", src: "roms/nes/lolo3.nes" },
    { title: "Adventures of Tom Sawyer", system: "nes", img: "", src: "roms/nes/tomsawyer.nes" },
    { title: "Air Fortress", system: "nes", img: "", src: "roms/nes/airfort.nes" },
    { title: "Al Unser Jr.'s Turbo Racing", system: "nes", img: "", src: "roms/nes/turboracing.nes" },
    { title: "Aladdin", system: "nes", img: "", src: "roms/nes/aladdin.nes" },
    { title: "Alfred Chicken", system: "nes", img: "", src: "roms/nes/alfred.nes" },
    { title: "Alien 3", system: "nes", img: "", src: "roms/nes/alien3.nes" },
    { title: "Alien Syndrome", system: "nes", img: "", src: "roms/nes/aliensynd.nes" },
    { title: "All-Pro Basketball", system: "nes", img: "", src: "roms/nes/allprobball.nes" },
    { title: "Alpha Mission", system: "nes", img: "", src: "roms/nes/alphamis.nes" },
    { title: "Amagon", system: "nes", img: "", src: "roms/nes/amagon.nes" },
    { title: "American Gladiators", system: "nes", img: "", src: "roms/nes/gladiators.nes" },
    { title: "Ancient Chinese Secret", system: "nes", img: "", src: "roms/nes/chinesesecret.nes" },
    { title: "Animal Crossing", system: "nes", img: "", src: "roms/nes/animalcross.nes" },
    { title: "Anticipation", system: "nes", img: "", src: "roms/nes/anticip.nes" },
    { title: "Arch Rivals", system: "nes", img: "", src: "roms/nes/archrivals.nes" },
    { title: "Arkanoid", system: "nes", img: "", src: "roms/nes/arkanoid.nes" },
    { title: "Arkanoid II: Revenge of Doh", system: "nes", img: "", src: "roms/nes/arkanoid2.nes" },
    { title: "Astyanax", system: "nes", img: "", src: "roms/nes/astyanax.nes" },
    { title: "Atlantis no Nazo", system: "nes", img: "", src: "roms/nes/atlantis.nes" },
    { title: "Attack of the Killer Tomatoes", system: "nes", img: "", src: "roms/nes/tomatoes.nes" },
    { title: "Austrian Grand Prix", system: "nes", img: "", src: "roms/nes/austriangp.nes" },
    { title: "Auto Racing", system: "nes", img: "", src: "roms/nes/autorace.nes" },
    { title: "Avenging Spirit", system: "nes", img: "", src: "roms/nes/avenging.nes" },
    { title: "Bad Dudes vs. DragonNinja", system: "nes", img: "", src: "roms/nes/baddudes.nes" },
    { title: "Bad News Baseball", system: "nes", img: "", src: "roms/nes/badnewsbb.nes" },
    { title: "Balloon Fight", system: "nes", img: "", src: "roms/nes/balloon.nes" },
    { title: "Barbie", system: "nes", img: "", src: "roms/nes/barbie.nes" },
    { title: "Bard's Tale, The", system: "nes", img: "", src: "roms/nes/bardstale.nes" },
    { title: "Barker Bill's Trick Shooting", system: "nes", img: "", src: "roms/nes/trickshoot.nes" },
    { title: "Baseball", system: "nes", img: "", src: "roms/nes/baseball.nes" },
    { title: "Baseball Stars 2", system: "nes", img: "", src: "roms/nes/baseballstars2.nes" },
    { title: "Bases Loaded", system: "nes", img: "", src: "roms/nes/basesloaded.nes" },
    { title: "Bases Loaded II", system: "nes", img: "", src: "roms/nes/basesloaded2.nes" },
    { title: "Bases Loaded III", system: "nes", img: "", src: "roms/nes/basesloaded3.nes" },
    { title: "Bases Loaded IV", system: "nes", img: "", src: "roms/nes/basesloaded4.nes" },
    { title: "Batman", system: "nes", img: "", src: "roms/nes/batman.nes" },
    { title: "Batman: Return of the Joker", system: "nes", img: "", src: "roms/nes/batmanjoker.nes" },
    { title: "Batman Returns", system: "nes", img: "", src: "roms/nes/batmanreturns.nes" },
    { title: "Battle Chess", system: "nes", img: "", src: "roms/nes/battlechess.nes" },
    { title: "Battle of Olympus", system: "nes", img: "", src: "roms/nes/olympus.nes" },
    { title: "Battletoads", system: "nes", img: "", src: "roms/nes/battletoads.nes" },
    { title: "Battletoads & Double Dragon", system: "nes", img: "", src: "roms/nes/battletoadsdd.nes" },
    { title: "Beetlejuice", system: "nes", img: "", src: "roms/nes/beetlejuice.nes" },
    { title: "Bible Adventures", system: "nes", img: "", src: "roms/nes/bibleadv.nes" },
    { title: "Bionic Commando", system: "nes", img: "", src: "roms/nes/bionic.nes" },
    { title: "Black Bass", system: "nes", img: "", src: "roms/nes/blackbass.nes" },
    { title: "Blades of Steel", system: "nes", img: "", src: "roms/nes/bladessteel.nes" },
    { title: "Blaster Master", system: "nes", img: "", src: "roms/nes/blasterm.nes" },
    { title: "Blue Marlin", system: "nes", img: "", src: "roms/nes/bluemarlin.nes" },
    { title: "The Blue Marlin", system: "nes", img: "", src: "roms/nes/bluemarlin2.nes" },
    { title: "Bo Jackson Baseball", system: "nes", img: "", src: "roms/nes/bojackson.nes" },
    { title: "Bomberman", system: "nes", img: "", src: "roms/nes/bomberman.nes" },
    { title: "Bomberman II", system: "nes", img: "", src: "roms/nes/bomberman2.nes" },
    { title: "Bonk's Adventure", system: "nes", img: "", src: "roms/nes/bonk.nes" },
    { title: "Boulder Dash", system: "nes", img: "", src: "roms/nes/boulderdash.nes" },
    { title: "Boxing", system: "nes", img: "", src: "roms/nes/boxing.nes" },
    { title: "Bram Stoker's Dracula", system: "nes", img: "", src: "roms/nes/dracula.nes" },
    { title: "BreakTime", system: "nes", img: "", src: "roms/nes/breaktime.nes" },
    { title: "Bubble Bobble", system: "nes", img: "", src: "roms/nes/bubblebobble.nes" },
    { title: "Bucky O'Hare", system: "nes", img: "", src: "roms/nes/buckyohare.nes" },
    { title: "Bugaboo (The Flea)", system: "nes", img: "", src: "roms/nes/bugaboo.nes" },
    { title: "Bump 'n' Jump", system: "nes", img: "", src: "roms/nes/bumpnjump.nes" },
    { title: "Burai Fighter", system: "nes", img: "", src: "roms/nes/buraifighter.nes" },
    { title: "BurgerTime", system: "nes", img: "", src: "roms/nes/burgertime.nes" },
    { title: "Cabal", system: "nes", img: "", src: "roms/nes/cabal.nes" },
    { title: "Caesars Palace", system: "nes", img: "", src: "roms/nes/caesars.nes" },
    { title: "California Games", system: "nes", img: "", src: "roms/nes/californiagames.nes" },
    { title: "Capcom's Gold Medal Challenge '92", system: "nes", img: "", src: "roms/nes/goldmedal.nes" },
    { title: "Captain America and The Avengers", system: "nes", img: "", src: "roms/nes/captainamerica.nes" },
    { title: "Captain Planet and the Planeteers", system: "nes", img: "", src: "roms/nes/captainplanet.nes" },
    { title: "Castelian", system: "nes", img: "", src: "roms/nes/castelian.nes" },
    { title: "Castlevania", system: "nes", img: "", src: "roms/nes/castlevania.nes" },
    { title: "Castlevania II: Simon's Quest", system: "nes", img: "", src: "roms/nes/castlevania2.nes" },
    { title: "Castlevania III: Dracula's Curse", system: "nes", img: "", src: "roms/nes/castlevania3.nes" },
    { title: "Caveman Games", system: "nes", img: "", src: "roms/nes/caveman.nes" },
    { title: "Championship Bowling", system: "nes", img: "", src: "roms/nes/champbowl.nes" },
    { title: "Championship Pool", system: "nes", img: "", src: "roms/nes/champpool.nes" },
    { title: "CheetahMen", system: "nes", img: "", src: "roms/nes/cheetahmen.nes" },
    { title: "CheetahMen II", system: "nes", img: "", src: "roms/nes/cheetahmen2.nes" },
    { title: "Chip 'n Dale Rescue Rangers", system: "nes", img: "", src: "roms/nes/chipndale.nes" },
    { title: "Chip 'n Dale Rescue Rangers 2", system: "nes", img: "", src: "roms/nes/chipndale2.nes" },
    { title: "Chubby Cherub", system: "nes", img: "", src: "roms/nes/chubbycherub.nes" },
    { title: "Circus Caper", system: "nes", img: "", src: "roms/nes/circus.nes" },
    { title: "Circus Charlie", system: "nes", img: "", src: "roms/nes/circuscharlie.nes" },
    { title: "City Connection", system: "nes", img: "", src: "roms/nes/cityconn.nes" },
    { title: "Clash at Demonhead", system: "nes", img: "", src: "roms/nes/demonhead.nes" },
    { title: "Classic Concentration", system: "nes", img: "", src: "roms/nes/concentrat.nes" },
    { title: "Cobra Command", system: "nes", img: "", src: "roms/nes/cobracommand.nes" },
    { title: "Cobra Triangle", system: "nes", img: "", src: "roms/nes/cobratriang.nes" },
    { title: "Code Name: S.T.E.A.M.", system: "nes", img: "", src: "roms/nes/codename.nes" },
    { title: "Color a Dinosaur", system: "nes", img: "", src: "roms/nes/colordino.nes" },
    { title: "Commando", system: "nes", img: "", src: "roms/nes/commando.nes" },
    { title: "Conan", system: "nes", img: "", src: "roms/nes/conan.nes" },
    { title: "Conflict", system: "nes", img: "", src: "roms/nes/conflict.nes" },
    { title: "Conquest of the Crystal Palace", system: "nes", img: "", src: "roms/nes/crystalpalace.nes" },
    { title: "Contra", system: "nes", img: "", src: "roms/nes/contra.nes" },
    { title: "Contra Force", system: "nes", img: "", src: "roms/nes/contraforce.nes" },
    { title: "Cool World", system: "nes", img: "", src: "roms/nes/coolworld.nes" },
    { title: "Cowboy Kid", system: "nes", img: "", src: "roms/nes/cowboykid.nes" },
    { title: "Crackout", system: "nes", img: "", src: "roms/nes/crackout.nes" },
    { title: "Crazy Climber", system: "nes", img: "", src: "roms/nes/crazyclimb.nes" },
    { title: "Crystalis", system: "nes", img: "", src: "roms/nes/crystalis.nes" },
    { title: "Cybernoid", system: "nes", img: "", src: "roms/nes/cybernoid.nes" },
    { title: "Cybernoid II: The Revenge", system: "nes", img: "", src: "roms/nes/cybernoid2.nes" }

    
    
   
]);