x= "https://drive.google.com/thumbnail?id="
agregarJuegos([
    { system: "nes", img: x+ "1jKRthY7Cx356aVCMyOjqieDV5qj-xnPt", title: "DETH COMPLEX 2", src: "dethcomplex2.nes" },
    { system: "nes", img: x+ "10Qzz4bcGnNBO71gSqtnRcWEpAKVNcHBx", title: "MAGICAL DUNGEON 3D", src: "magicaldungeon3d.nes" },
    { system: "nes", img: "1obaks5fuTIq311mTSgHdgAH3xVQOwhSF", title: "PONG TMNT TRILOGY", src: "pongtmnttrilogy.nes" },
    
    
    
    { system: "nes", img: "1lSO7bxZ685Fgyi9BhmOlt9qR-S9jhJjV", title: "A NIGHTMARE ON ELM STREET" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    { system: "nes", img: "", title: "", src: "" },
    
    
    
    
    
   
]);