function pa(a, b, c, d, e, f, g) {
     x= "https://drive.google.com/thumbnail?id=1";
     y= "https://1024terabox.com/s/1";   
     return {
          image: x + a, youtube: b, terabox: y + c, title: d, subtitle: e, subtitle2: f, search: g
     };
};

const data_peliculasA= [
     { id: "PelículasA", data: [
          pa("nF3N6Fhq5HyNXm84T9RlU1rkEq6_8jk9","6MzJkz7lzg8","qiik6TSH3IhOBZ-J4AqXJA","A BOY NAMED CHARLIE BROWN","","","charlie brown, snoopy, un niño llamado charlie brown, 1969"),
          pa("HZznjYYXmwaOdcZHx6JSAXpXRRd4ELiE","yPPycZo8H7c","3V_JEGPsj-7PKvBpZKjvew","A BRIDGE TOO FAR","","","un puente muy lejano, 1960, peroiz#g"),
          pa("RHgNLG2JE43LkaKNVNSgjXSXPqFbucPO","z50PjmZYS4A","UxP8gLvCCz28xiB8kyPrJw","A BRONX TALE","","","una historia del bronx, 1993, peroiz#g"),
          pa("RNTRI4twVd75Shysh4NbciAP8L66GMqi","v3TCRX9TDXE","ZnOviSPaNhZ_rziOC_13Zg","A CURE FOR WELLNESS","","","la cura siniestra, 2016"),
          pa("DO7sAVRzeac4Lr-cxuUwvIT9XO7y5jp5","1pKdCHvH310","GH4J9O81WIcw-AHWOg813g","A DOG\'S WAY HOME","","","mis huellas a casa, 2019"),
          pa("vEcvF48YZaRYdrcD9WV-g9VYLNa6wfCq","yEddsSwweyE","kKHuN39FK-4Mrqpsk-VI3Q","A HAUNTING IN VENICE","","","misterio en venecia, 2023"),
          pa("xawMESDAp4XLw4RZJoHlwWccBBNWNPYg","aJzcWbh-Awo","T6HDOa6IfxlNdxin0P2kMg","A MILLION WAYS TO DIE IN THE WEST","","","mil maneras de morder el polvo, 2014"),
          pa("Q3cEfRHHfNVyUGibX1wc-Xsrguqiayqk","Xzwt7do8Mpk","h-Hcx6W2lDDpvL3f30OHsw","A NIGHTMARE ON ELM STREET","","","pesadilla en la calle del infierno, 1984, a nightmare on elm street, a nightmare on elm street 2 freddys revenge, a nightmare on elm street 3 dream warriors, a nightmare on elm street 4 the dream master, a nightmare on elm street 5 the dream child, a nightmare on elm street 6 freddys dead the final nightmare"),
          pa("wYym50bv67LTmO3de2Rfkk9DXTn9XF-e","Vt6ktXKie7M","ZI5qX7xS9dwpo8MIm4pMaQ","A NIGHTMARE ON ELM STREET 2 FREDDY\'S REVENGE","","","pesadilla en la calle del infierno 2 la venganza de freddy, 1985, a nightmare on elm street, a nightmare on elm street 2 freddys revenge, a nightmare on elm street 3 dream warriors, a nightmare on elm street 4 the dream master, a nightmare on elm street 5 the dream child, a nightmare on elm street 6 freddys dead the final nightmare"),
          pa("eeGDpYNDJ7sqtc2JHDhwpEfLNjhmBbtb","oy-hgBu1h0w","tR9UlOXQS8dWNIFsokIipQ","A NIGHTMARE ON ELM STREET 3 DREAM WARRIORS","","","pesadilla en la calle del infierno 3 guerreros del sueño, 1987, a nightmare on elm street, a nightmare on elm street 2 freddys revenge, a nightmare on elm street 3 dream warriors, a nightmare on elm street 4 the dream master, a nightmare on elm street 5 the dream child, a nightmare on elm street 6 freddys dead the final nightmare"),
          pa("CIn_jmkc5NAqEYBN7nzRheo-tUGAB-y4","2m1a2Pt8Vjw","j21O9aqAeIpTiQSNoPht0A","A NIGHTMARE ON ELM STREET 4 THE DREAM MASTER","","","pesadilla en la calle del infierno 4 el amo del sueño, 1988, a nightmare on elm street, a nightmare on elm street 2 freddys revenge, a nightmare on elm street 3 dream warriors, a nightmare on elm street 4 the dream master, a nightmare on elm street 5 the dream child, a nightmare on elm street 6 freddys dead the final nightmare"),
          pa("E-3LcFTKlM-j-yr8jKeGAvGorSR9qJ8I","jSj7LPQ8U1A","S8-WNI8TLA4h8waPzoaWeQ","A NIGHTMARE ON ELM STREET 5 THE DREAM CHILD","","","pesadilla en la calle del infierno 5 el niño de los sueños, 1989, a nightmare on elm street, a nightmare on elm street 2 freddys revenge, a nightmare on elm street 3 dream warriors, a nightmare on elm street 4 the dream master, a nightmare on elm street 5 the dream child, a nightmare on elm street 6 freddys dead the final nightmare"),
          pa("SLeClq0X_QN_QKzTK8QngEouRkkxWbza","Vm5PYf1WqMQ","dSSsNZWNn9c3PeXv-IPiVA","A NIGHTMARE ON ELM STREET 6 FREDDY\'S DEAD, THE FINAL NIGHTMARE","","","pesadila en la calle del infierno 6 freddy ha muerto, 1991, a nightmare on elm street, a nightmare on elm street 2 freddys revenge, a nightmare on elm street 3 dream warriors, a nightmare on elm street 4 the dream master, a nightmare on elm street 5 the dream child, a nightmare on elm street 6 freddys dead the final nightmare"),
          pa("egx4MhA1D00VWkjAM8CnR5be0fgXa7Of","ZuYoEtEI_go","xvK2BUvITVlUs9l2eegksg","A NIGHTMARE ON ELM STREET","","","pesadilla en la calle del infierno, 2010, a nightmare on elm street, a nightmare on elm street 2 freddys revenge, a nightmare on elm street 3 dream warriors, a nightmare on elm street 4 the dream master, a nightmare on elm street 5 the dream child, a nightmare on elm street 6 freddys dead the final nightmare"),
                   pa("23kUvg3Sb9tWYHP6RK1Ap9_UNLyrxVc5","b2et8Vpu7Ls","86nV5NPquTGJiYiCUdQuEg","A REAL PAIN","","","un dolor real. 2024"),
          pa("_pCnVPgLMl3VmYwj9jwNBLT97WVcufPy","4YmCIp4qlGg","fmhrkc6xzmFffEEqNBGrcA","A TALE OF TWO SISTERS","","","dos hermanas, 2003"),
          pa("798pmYBWT_HpTIJw9ayCfWLlRpnw_6Ex","Jc4ZkA_9xKc","8X16CDItdEw9On1T92NIAA","A TODA MAQUINA","","","pedro infante, luis aguilar, 1951, que te ha dado esa mujer"),
          pa("kq8OQxLSc_4vQx78toSO0xs4SqMYyc6D","cOMRJy1_vJA","-s4Jrze5s4n1TqumvrCFoQ","A VOLAR JOVEN!","","","mario moreno cantinflas, a volar joven, 1947"),
          pa("HqHeHiEEho6L0XO4kxjxpVwPkSCHkv7E","8Qcgo0Ep0C4","xpmfXWR61S4oGWC2qvw6_Q","A WHISKER AWAY","","","amor de gata, 2020"),
          pa("j3qIijsnJYVeTFE5ZraxmsMlAKWEfcK-","q03DhtMW_qE","dIm5VmhyJ6BmpM4sW-m8_g","A. D. THE BIBLE CONTINUES","TEMPORADA 1","","biblia, a. d. la biblia continua, 2015"),
          pa("pHeZZCt9N2dWxqGxr8nuJSSYAwXIJTme","_19pRsZRiz4","VDGZfG1v8fhe2P2zEF5FEA","A. I. ARTIFICIAL INTELLIGENCE","","","i. a. inteligencia artificial, 2001"),
          pa("flKEYJ_2no8q5iuGHJgjqZLesnUFqJx-","22sIQyPqRsY","NT-KUpuUKLIppuhba70CGQ","A. X. L.","","","2018"),
          pa("cQpgLvnv4QwxafrCUD2D4pfvbsjDUVoH","5vi8GQov5Wc","QCbxTVBT55XPZZOr97YwJw","ABAJO EL TELÓN","","","mario moreno, cantinflas, 1955"),
          pa("YLIjXkChStkaJdpngR4x4Z6qZR7wXVFP","fnn9zEQbqI0","kT5C5eYZ4bgjMcKr4-Y5NQ","ABBEY ROAD IF THESE WALLS COULD SING","[ Español || Español ]","","si estas paredes cantaran, 2022"),
          pa("_OEaXpMcEXohVQ6qehvb7Ra9m3XwcN6O","goSOXI2XkIA","skb5vrUmmNjf_98iFtL7Wg","ABOMINABLE","","","un amigo abominable, 2019"),
          pa("JZaGwF13gYPrl8QHG5zPLtdSVgyE6rZ7","lMHXh7qdIV4","hhRw9Oav2Gv8kMWBUp9vjw","THE ABYSS","","","el abismo de kiruna, 2023"),
          pa("yYEmh5Q4fgvI0hooDlwmD3fj7X2wKFS7","Sg7Il74pOxE","yOr9U_3rumchJqXr_PgS6A","ACE VENTURA PET DETECTIVE","","","jim carrey, ace ventura detective de mascotas, 1994, ace ventura 2 when nature calls"),
          pa("hT6vd7BuhtX5-kLcGyoRIwwpgrSJ0u74","zcsANwPMKNg","l2ZKPuU27qUUoZYnjrPgYA","ACE VENTURA 2 WHEN NATURE CALLS","","","jim carrey, ace ventura 2 cuando la naturaleza llama, 1995, ace ventura pet detective"),
          pa("lstt40jWgC_EkbcjyDCsiNYlCcRz0fgm","P6AaSMfXHbA","A9ry4VQQFDtDtjbT9Q6QYw","AD ASTRA","","","hacia las estrellas, 2019"),
          pa("9x8brUnsDfR7gS-dBJO3BfZVSQQAS-Lt","cfawtDT945o","qokyRdzIEoOKl9XIG5PNfQ","THE ADDAMS FAMILY","TEMPORADA 1","","los locos addams, 1964, the addams family, addams family values, the addams family 2, peroiz#g"),
          pa("7ula_bZ3kUyBbXM39uMcL109G_dwd4UJ","cfawtDT945o","SKl7XXCUvKU_ZGLMnLQ7qA","THE ADDAMS FAMILY","TEMPORADA 2","","los locos addams, 1965, the addams family, addams family values, the addams family 2, peroiz#g"),
          pa("3sx3aSbxN5vQ7TQ1PRg5hTPXuJyC_NtO","G388UMkJIBE","IL1gf6AzDPgABKLJflqcIw","THE ADDAMS FAMILY","","","los locos addams, 1991, the addams family, addams family values, the addams family 2"),
          pa("-WaMcEJET0u-n_Hrfc-asd2FPpubhzsr","Bb2FTulPpOA","hRzXwPgn-Iw32dLNhnB5aQ","ADDAMS FAMILY VALUES","","","los locos addams 2 la tradicion continua, 1993, the addams family, addams family values, the addams family 2"),
          pa("jv3S3CtD_mbrzw5d4m9e8-cAM6sinfl9","xFCrR3Uw6Mk","gf9AbiWZyrpWKLnhwZGLkA","THE ADDAMS FAMILY","","","los locos addams, 2019, the addams family, addams family values, the addams family 2"), 
          pa("7wpSf2g5LjY25mR0R4mA33Jd7mFJ-3Ek","946LiJiMQrQ","cU131y6V8AuL_P_aZHd8lg","THE ADDAMS FAMILY 2","","","los locos addams 2, 2021, the addams family, addams family values, the addams family 2"),
          pa("J89RFUWQx4r7Js2Pv0PfPggRnP_aXTyL","If2lCD0SQrE","z6GLwOARhU73TPmj-gqAOA","ADRIFT","","","a la deriva, 2018"),
          pa("5jeDi2V5vRefU0lxwdEsH23k8N7kI8VD","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 1","","hora de aventura, 2010, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("OusdtzVpVkHGcFVpeFJ7wl5cg2Od5kfe","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 2","","hora de aventura. 2010, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("gIiCIYxwoUMgi9Oswrt3fzL-f6UIR3bp","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 3","","hora de aventura, 2011, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("jWwmzPKkr6MKcA5iYkSpJ5dPycVcWl01","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 4","","hora de aventura, 2012, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("UckgMKgC9r_4X3nKiJIMYs5_ZTdNKqBg","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 5","","hora de aventura, 2012, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("TC3SW-lQamdtfxI8nHTvEb1OnF8_TcpN","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 6","","hora de aventura, 2014, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("c5ZoSPuC_Gfl1RGuCqQvcsmFOSx4TxWA","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 7","","hora de aventura, 2015, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("4f8EHKmj6QYR2EZWS2Q9HT5x0YAlRlfS","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 8","","hora de aventura, 2016, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("GR8ZwLK_EXPTLJJzOkXZC0y7USLA2gDG","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 9","","hora de aventura, 2017, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("BMJiuVyL2wGsXdHDcjJHCISw7JsDk3Sm","8EAqF_6N3tY","uNUf8tKbOF0SeposiCJE5w","ADVENTURE TIME","TEMPORADA 10","","hora de aventura, 2017, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("uEicnrHKT5U75vpdHu2mNufXUqe0e8lA","8EAqF_6N3tY","1pdcUQFihPFh6zJZt9D_RA","ADVENTURE TIME FROG SEASONS MINISODES","TEMPORADA 1","","hora de aventura estaciones de la rana, 2016, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("nlnQTMqq0qKA5rkzpLF3FKJtg8CFAEwP","OXp-_NvO4JY","-dsgeOlPCsGIy4U4FUt8Sw","ADVENTURE TIME GRAYBLES ALLSORTS","TEMPORADA 1","","hora de aventura fabulas variadas, 2017, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("6TmXF6A2OLLuyoF2AQtknZgKnZD6t9cy","-e_Q154xjts","5nbF11mEG12cDvYA7PCFzg","ADVENTURE TIME DISTANT LANDS","TEMPORADA 1","","hora de aventura tierras lejanas, 2020, adventure time, adventure time distant lands, adventure time frog seasons minisodes. adventure time graybles allsorts"),
          pa("uIhJMD3NJc20HBjlEmkjEQz9AfcLCiKd","CdZ1Y92eVfM","U63GWb1YPLuyjxJrr-4NNQ","THE ADVENTURES OF ICHABOD AND MR. TOAD","","","el jinete sin cabeza, las aventuras de ichabod y el señor sapo, 1949"),
          pa("ZFHvgzu6zHs2dgGdYHsm94kLLLaNLDV3","D93cDpwWL-k","-KDE1cXADOAjEmscReMSvA","AFTER","","","after aqui empirza todo, 2019, after, after 2 we collided, after 3 we fell, after 4 ever happy, after 5 everything"),
          pa("ZInaOl8xIJ-2HUUFBRCD5W6aD5qfBSKS","2SvwX3ux_-8","yfrtozGX3pknzsit5xH7fw","AFTER 2 WE COLLIDED","","","after 2 en mil pedazos, 2020, after, after 2 we collided, after 3 we fell, after 4 ever happy, after 5 everything"),
          pa("2yURDZdnDEBfhH5dPgPDEATyut5XYM_N","NYdNN6C9hfI","L5gNUh4kW21GNjfRfkd4Bw","AFTER 3 WE FELL","","","after 3 almas perdidas, 2021, after, after 2 we collided, after 3 we fell, after 4 ever happy, after 5 everything"),
          pa("OU_njPmow-zjb42nupodnqoxltLxwbqt","hLQ-5exgctI","BPy8lnHiOZe7D6a2iwkY_Q","AFTER 4 EVER HAPPY","","","after 4 amor infinito, 2022, after, after 2 we collided, after 3 we fell, after 4 ever happy, after 5 everything"),
          pa("n5hMRf85ZJ0X5MIfH_j5eKJwwP1bY0vx","KFO3kw7AZME","K2CtTsbp-cr0KKTAmCadDA","AFTER 5 EVERYTHING","","","after 5 para siempre, 2023, after, after 2 we collided, after 3 we fell, after 4 ever happy, after 5 everything"),
                    pa("DjBH8MVQgk600BR1aKv-LECJ5_81t4d5","A6VATGruY-U","Q3j__NPQHmKco2K1Z8JSJA","AGENT JADE BLACK","","","jade black la agente secreta, 2020"),
          pa("xAQSGxBMnPzrdNMW8_qfjnMS7oOIouXC","DJWqA-UZwaM","1QAcj97RUu616V0THi0fuw","ÁGUILA O SOL","","","mario moreno cantinflas, aguila o sol, 1937"),
          pa("8OLoysCjz_B85XUtWI_pAvhJf4XmpbBe","mfBq54zhqqM","fzjnHng-zKG26qNArrVOjA","AHI ESTA EL DETALLE","","","mario moreno cantinflas, ahi esta el detalle, 1940"),
          pa("3hRPxdzkx3qrSiJlnwsjXM9pzU0Ry0Dq","2hbkX2iAOug","sCsksLd75AxbA7T0On-p8A","AIR STRIKE","[ Ing || Esp ]","","bruce willis, el bombardero, 2018"),
          pa("FhowMC6-u3TSRRsMxRqz_J9COO-FqkPI","07pPmCfKi3U","L5ZLs8HaXZu8V9o7oqeL8A","AIRPLANE !!","","","y donde esta el piloto, 1980, airplane 2 the sequel"),
          pa("si4T_jDLgO5R3VfTvfVL552NHQ-fmDfX","sRenGGLeDKk","acySmHDCNkVsmcY7WLyP7g","AIRPLANE !! 2 THE SEQUEL","","","y donde esta el piloto 2 1982, airplane"),
          pa("kPB-NXoKSHx_t6KDA6CDS4QPYNWGUl4u","nA8KmHC2Z-g","U-kbN2AAqledSENIT8pa7Q","AKIRA","","","1988"),
          pa("pxCBi2Bc2xbU5nIA8NMOwsqq4T46iWaK","eTjHiQKJUDY","wlpIDd8aO7cu8fTBFHXG7Q","ALADDIN","","","aladdin, 1992"),
          pa("mb-rSC0BL_YwG_OuThOuK2Oox6aHF3ds","5DPTNSFHH_w","kecHbhjqb5GepzwupJAvMg","ALADDIN","Aladdin (2019)","","will smith, aladdin, 2019"),
          pa("W8I4w0_usbmNyiYi_vu6oNfly5bTHE0q","PA-h3-0wheo","Yn1rbUNJUKQVKynpra68_A","ALICE IN WONDERLAND","","","alicia en el pais de las maravillas, 1940, alice in wonderland, alice through the looking glass"), 
          pa("2svpnOA8T7Rj53Fg4sXkYI4JKjsUYcP6","5aTMU12s-9g","B9gytCarp9Z0RfSbkskyIQ","ALICE IN WONDERLAND","","","johnny deep, mia wasikowska, helena bonham carter, anne hathaway, alicia en el pais de las maravillas. 2010, alice in wonderland, alice through the looking glass"),
          pa("iJBmKtVWXBCc6zcT23rB7eTTHR4ELC2B","","lpr_BYUfWoAqxSlixXVFGQ","ALICE THROUGH THE LOOKING GLASS","","","johnny deep, mia wasikowska, helena bonham carter, anne hathaway, Sacha Baron Cohen, alicia a traves del espejo, 2016, alice in wonderland, alice through the looking glass"),
          pa("YGdhVsiZszMUllao99ovdJveC-Ppsjpk","Eu9ZFTXXEiw","_1w__NspXZcLqL42Ax0APA","ALIEN","Alien El Octavo Pasajero (1979)","","alien el octavo pasajero, 1979, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth"),
          pa("_3iui4LC6M04ueY6zEQ4mtoVjf1OwA6J","Rfmq2PGjrko","HJY1ZkAF-jOwSgmTZKX69g","ALIENS","","","alien 2 el regreso, 1986, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth"), 
          pa("emQa-1b1aFs_aai2RhU1onfd-2BwJ8Vp","Ipv1y-Phi7A","2XXlIw18cs2Xh0s92UJNtA","ALIEN³","","","alien 3, 1992, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth"),
          pa("BGv-uVK093eBn-BgqeiCOoFJQ7Fu1zHb","15g12dGxWX4","DaUqItGX3M0RqoGZC0uy1Q","ALIEN RESURECTION","","","alien 4 resurreccion, 1997, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth"),
          pa("E0llzLpyVa7bBMTcVEAvwhwKbU6zK2bm","yztZpU-8yOI","SNBAVEBl56LgJ8elR04uug","ALIEN COVENANT","","","2017, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth"),
          pa("5f2SMhd2Dv1HvI1Ky8cvdJ1fYElc9kzU","GTNMt84KT0k","AVUCkRMjWhWOtqcfbyY3tQ","ALIEN ROMULUS","","","2024, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth"),
          pa("xcpi_qNxXSCG5fsovaMxHYzJJR7ulwJ_","eotAOKm4l18","zRA0mxO0XUhmOkN3iEOHQA","ALIEN: EARTH","TEMPORADA 1","","alien planeta tierra, 2025, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth"),
          pa("15pGrlXwDGVManLp2dLds67_yxaSpYHS","Cld40qD7HcY","_dza2wR_5RcU_hTfaev-Hg","ALIEN VS. PREDATOR","","","alien vs depredador, 2004, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth, alien vs predator, alien vs predator 2 requiem"), 
          pa("OruzHi2yPfkBMRYEJ6MhhBZANIfcPNC7","JtydkHQeBFM","DF9t9zD9qwGJ-TpzL-F28A","ALIEN VS. PREDATOR 2 REQUIEM","","","alien vs depredador 2 , 2007, alien, aliens, alien³, alien resurection, alien covenant, alien romulus, alien earth. alien vs predator, alien vs predator 2 requiem"),
          pa("DarMOj227HnoknyfnyTI2y2YO6wpHngD","zq1YMc4C6GkrVjggiLVXFA","ALIEN AGENT","[ Español ]","","agente alien, 2007"),
          pa("drt3tp7kg0yRtMFW7phv2btv07wezu8j","bE__oBVuzSw","hUwrayvihp1BLxPDWHzS-A","ALIEN WARFARE","","","2019"),
          pa("Ize-5fkyGCi1m0xNJEQBInqFSOc48x9q","w7pYhpJaJW8","D65lDx_vxfW5o-eDfM8_yQ","ALITA BATTLE ANGEL","","","alita angel de batalla, 2019"), 
          pa("aRszSpNYk8mBuk9F8OOTA3qV6bUBt8_A","0f1_fbdB6RQ","mia8ZGM_iq9hL1gPv65MGA","ALLIED","Aliados (2016)","","brad pitt, aliados, 2016"), 
          pa("4lS15Wvr3dgP053u98NeCtGDRDr0G1Oj","tJk5yw7FIzk","X-rVGgucQYoEE96wluUKWg","ALMIGHTY ZEUS","","","el poderoso zeus, 2022"),
          pa("X--qFCVuxMPry82UfdTE1sbiMtN4Ii0m","qKh-uufIh9w","HDu1Qkuk1E1LjIlNFOQ2zg","ALONG WITH THE GODS THE LAST 49 DAYS","","","junto a los dioses los ultimos 49 dias, 2018, along with the gods the last 49 days, along with the gods the two worlds"), 
          pa("FnevA3fI0OrRAyYMkna7SiwZHDgT0iyI","sD7dmu-IWNw","VFTRBUoKMGrvCd2S-4z4pA","ALONG WITH THE GODS THE TWO WORLDS","","","junto a los dioses los dos mundos, 2017, along with the gods the last 49 days, along with the gods the two worlds"),
          pa("6vYyFetfSpB7VnMJ2SahfEg7AqYn0CMh","SlL_6bDSd8E","eWvo-9pCJ-jTj3lcQm5nrw","ALPHA","","","alfa, 2018,"), 
          pa("eciBpK6HsbbCdQrj-tvzwJ-ahNxlApHo","HmDxxoFslzs","Vx6FYNQJxTPiTNdLEk6gKw","ALTERED CARBON RESLEEVED","","","altered carbon reenfundados, 2020"), 
          pa("d2oMi2g5Vz04iwnXI41x2BhGxl06UBM1","xA6cOSEZhzM","MypeAd-h2cAddu2RD2fOAA","ALVIN AND THE CHIPMUNKS THE ROAD CHIP","","","alvin y las ardillas aventura sobre ruedas, 2015"),
          pa("KCJg_CXo03hOql73ydCyr7gTs2f4Cje7","bGHyRxaT_9o","9jHfXMu6lrtk9R4_HHUPkw","AMERICAN BEAUTY","","","belleza americana, 1999, peroiz#g"),
          pa("qqYllVWtmXFU7rnsAJa-UfGaOLCjKxH9","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 1","","un agente de familia, 2005"),
          pa("5v1OwarajJZ_YLxK4xOUzHDphEKGIfBI","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 2","","un agente de familia, 2005"),
          pa("tggFNu5CWJgW70yHxkPyv-ptBnwyVtWX","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 3","","un agente de familia, 2006"),
          pa("z6GN4lEuHAyxBaAhtthS-OKIpK066xm2","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 4","","un agente de familia, 2007"),
          pa("dGiukaPqmSrHzqIyF0aFQcX8Ul7XiWvB","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 5","","un agente de familia, 2008"),
          pa("zxucuvw5nP4QSEExLdSHdXoeniKp-76f","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 6","","un agente de familia, 2009"),
          pa("SlmePylp9gGUknvEIEgDN-4dlZscp7FO","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 7","","un agente de familia, 2010"),
          pa("lN4oLCaOg1zUsR8x2Y_Wyp9lOlJHXlgY","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 8","","un agente de familia, 2011"),
          pa("ZKDczKNBvEnaijCpSG69o8jMjYVz3UxQ","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 9","","un agente de familia, 2012"),
          pa("Z6kDaWLtgeDDzHtCO0oYLPMVV4hmyfS4","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 10","","un agente de familia, 2013"),
          pa("47RwKr3bi17PqR2h-kaeWHkoO3ufwWsy","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 11","","un agente de familia, 2014"), 
          pa("GzBHTawBjAHfAl-KLYYzMXtjJzmCsYve","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 12","","un agente de familia, 2014"), 
          pa("1zT_tEL9A4-ttqOYlRc7Hzz_hKoKMlvU","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 13","","un agente de familia, 2016"),
          pa("8dAOBe9wEBlhuIrJTRt_OxbVBS0RBocP","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 14","","un agente de familia, 2016"), 
          pa("5CyexetNPzSNB3Sa2V5Oul-MfM0mnIxL","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 15","","un agente de familia, 2017"), 
          pa("AoIDKd3e5fx73MQbBmezpaBdl-1dohf8","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 16","","un agente de familia, 2019"), 
          pa("8tssICxD-v-0SEpG5hBLuwO_zL6lBJdU","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 17","","un agente de familia, 2020"),
          pa("5CNIXu0TD5bjrpufYZST-TJqJjw0X8Sf","3fKNf5dLA_M","NgYB8Y5Rp5qXvYgWMYwcLQ","AMERICAN DAD!","TEMPORADA 18","","un agente de familia, 2021"), 
          pa("j1Y_8vqUuTIZqJB3zc8YlaGBs604k46S","Nr9csFWtFts","ja1dPj8RFHNxJfgL59hkNw","AMERICAN GIGOLO","","","Richard gere, gigolo americano, 1990"), 
          pa("Vafl9s7AKAsegYWAwYBJl5RLVAdGSpXR","hqJtG7XNSmw","g_tt3KLfh9eOBN2e46ndlQ","AMERICAN GODS","TEMPORADA 1","","dioses americanos, 2017"),
          pa("vC3JrdWctgHDDL0j9k9s3Y9RmCLhuRNk","hqJtG7XNSmw","g_tt3KLfh9eOBN2e46ndlQ","AMERICAN GODS","TEMPORADA 2","","dioses americanos, 2019"),
          pa("oBtTL6rkbE3hr56Ywh0m5su-wPQ1RY9Y","hqJtG7XNSmw","g_tt3KLfh9eOBN2e46ndlQ","AMERICAN GODS","TEMPORADA 3","","dioses americanos, 2021"),
          pa("tStS-zn9JHYONrRt9qvdrX2pJRLwzEVT","EhrtmFC8sTE","wvwhCU7SEidqJT8bWEQXVw","AN AUDIENCE WITH ADELE","LONDON PALLADIUM","","en concierto con adele, 2021"),
          pa("tqkl73hpuAY4EBdQBOS84Nzu6yK_u9k5","KAquD5tmAn4","SSAI4UTQXGQbsuW0uwBnnA","ANASTASIA","","","1997, anastasia once upon a time"),
          pa("96oJI2Mcjlp_D5ceSckbwE9y-wVoo5Nz","OY0i_ThZtFg","gNyiO9f6skVb2tS_Vwp_UA","ANASTASIA ONCE UPON A TIME","","","erase una vez anastasia, 2020"),
          pa("W-LZn0KVy2CAugpQWqcX6-TaQQk3VkMT","jA_j1WNDd_Q","fKvc0KZgtWGGE3jhHSGDPw","ANGER MANAGEMENT","","","adam sandler, jack nicholson, locos de ira, 2003"),
          pa("lqY8AGo4yku3u6T-mB6hjq3puPXC7SJW","QRmKa7vvct4","1w38Gjnk3yW-pTx8I6nffw","THE ANGRY BIRDS MOVIE","","","angry birds la pelicula 2016, the angry birds movie, the angry birds 2 movie"), 
          pa("F1nPC-KHPLc6NPfPtP2Z99b81aw-t5Nq","EzdIQ-stR2k","_g_a6yh4wo8tb1iQy9IlTA","THE ANGRY BIRDS 2 MOVIE","","","angry birds 2 la pelicula, 2019, the angry birds movie, the angry birds 2 movie"), 
          pa("ZKV7Q9LnoVlgmELlsecGVHgpy0XyTkf7","pBwcksgKcFs","fos5xHRwG8Zho97ZkTUAjw","THE ANIMAL","","","Rob Schneider, Colleen Haskell, adam sandler, animal, 2001"), 
          pa("cmKNwT2qnSnVovUttcmxMM4U4Dp-f-_7","qn_FSTPmlT0","zBC17h0zi7Jgzfo6Zzjqfw","THE ANIMAL KINGDOM","","","criaturas asombrosas, 2023"),
          pa("WBDUEXCgpamlkPbyvUwwrYHWg5uwrqhv","xabuZwG3XyM","lAJsuA6eQoSFadM1uZ24wQ","ANNABELLE","","","anabel, 2014, annabelle annabelle comes home, annabelle creation"),
          pa("ip012aHKfDDorlzC9llZqY8ZMGV-x2xy","KisPhy7T__Q","xZlTRYT9ce7XlCMoulfWAw","ANNABELLE 2 CREATION","","","anabel 2 la creacion, 2017"), 
          pa("aW-AKyz-RZtW_Jqot_cKhUCSMl5EEnQr","ZL8fRl9oqjk","lAn4dK_JqHT4yJGb7oLWoQ","ANNABELLE 3 COMES HOME","","","anabel 3 vueve a casa, 2019"),          
          pa("erpVJQZ-W67OO1IMUBeB3ViTwd3tIVD0","xInh3VhAWs8","PBg5Sf_Q-xnxU3GnlWPehg","ANT-MAN","","","el hombre hormiga, 2015, antman, antman and the wasp, antman and the wasp 2 quantumania"), 
          pa("Bupue7jmHO-IGYbLbMlP8XeK-9QMqx-f","0QJE0dpYU6U","rx--jvOEWUqBnWoykSXlTA","ANT-MAN AND THE WASP","","","el hombre hormiga y la avispa, 2018, antman, antman and the wasp, antman and the wasp 2 quantumania"), 
          pa("o8_haaQNdo9emzhf99Y12nZCGykpkAim","ZlNFpri-Y40","pta00IqX7eyoiyO9Q8idXQ","ANT-MAN AND THE WASP 2 QUANTUMANIA","","","el hombre hormiga y la avispa 2 quantumania, 2023, antman, antman and the wasp, antman and the wasp 2 quantumania"),
          pa("Mm0bTbYio7bNMFrsWZVzYJ3v_41-kThc","OcslkrBMLGc","dc3dHJIDh1CShzp2xd39bw","THE APARTMENT","","","el apartamento, 1960"),
          pa("Hjek-hl5F-jRTt_CTxEG5tLeRq41HHro","0HEiqAsrVMQ","gCnBBxiJmuKnO7OcUuiReg","APOCALYPSE NOW","","","apocalipsis ahora, 1979"),
          pa("qxPfB6km1j_xJ2paQGAvYAF4QVbMnvj_","IfI0UE9s2as","XVXJNV-0M3KQdgT19nJf5w","APOCALYPSE THE SECOND WORLD WAR","TEMPORADA 1","","apocalipsis la segunda guerra mundial, 2009"), 
          pa("gu8oViggS9VyIpHFxbZYmILC1jB5mIR1","HvTnvWjM5gY","HCMxOWpc_TGa_xpIRdhdcg","APOCALYPSE D-DAY","TEMPORADA 1","","apocalipsis el dia d, 2024"),
          pa("rWwWARnjKXhZ5QAORtoEHiZ_822BnfLQ","pXuwjdQx924","sJZ8xTIFtC-u1vSLV6v1iQ","APOCALYPTO","","","mel gibson, 2006"), 
          pa("nWKB7ho7BG4KIjMEJPUHZA8VpayaJwBc","3Co8Z8BQgWc","8ui-NFpqlBn9u-bNaGFxfA","APOLLO 11","","","apolo 11, 2019 apollo 18"), 
          pa("a6zs5K4uPs0EWyeSQdDgkSqpwVUK-R8y","2YPEdDCEYuc","8jM4j6zA8dk_NgSrkbV0Pw","APOLLO 18","","","apolo 18, 2011 apollo 11"), 
          pa("pcdtKIy3P-H_WTG1fWZKL5ybr448ZhN2","iqowBGrKzuU","ur-aFm19hjC7r9BgluoxWw","APPENDAGE","","","el monstruo dentro de mi, 2023"), 
          pa("9ulNqGAQKFRGLUKwHso0woUV49B4Vzn0","2wcj6SrX4zw","atIoN2vDydJoOOPjOYT8pQ","AQUA-MAN","","","2018"), 
          pa("_ucqN3a19txSl4R7rhN1c1qK4HRji5UZ","gTNVXQ-GgFw","-cN5ZVktYw8jZlrt65Mo2w","ARE WE DONE YET ?","","","ice cube, una casa patas arriba, 2007"),
          pa("YD4BVqYefjGTM-OGQ-vVKa7-z6oh75Yj","zDCPJ3FH8hA","q4u_WaeCyAuAHNITwkc05g","THE ARISTOCATS","","","los aristogatos, 1970"),
          pa("HlU-BUvCbA_iuHuz5D9PPzge6BZ5sIEr","AwH0qJC3AUw","bYDB4IbX0JyxorQZal_2ig","ARMOR","Armadura (2024)","","Sylvester stalone armadura, 2024"),
          pa("p0HXwLNF2Zm3K5-lLafp-tLYGsK05KRZ","UHZQEtG8xYo","nmQ6d7JHQnVNaRRdBhe_cA","ARMY OF DARKNESS","","","el ejercito de las tinieblas, el despertar del diablo 3, 1992 the evil dead, evil dead 2, evil dead 3, army of darkness, evil dead, evil dead rise, evil dead burn"),
          pa("","0mvK6P2vr_o","bEfwl9db24IlwyBReyQwjQ","AROUND THE WORLD IN 80 DAYS","","","jackie chan, steve coogan, cecile de france, owen wilson, Arnold Schwarzenegger, la vuelta al mundo en 80 dias, 2004"),
          pa("2Lew7shrfQGoUrUMj0EwD_XL1Kt8_2bs","vjiCO8k6Jhg","tbtw7NARTup9O2ETWN_fcw","AROUND THE WORLD IN EIGHTY DAYS","La Vuelta Al Mundo En 80 Dias (1956)","","P3L01G"),
          pa("4MxhY4kHVCs1xT0AP6t78W4ROsV_4I1E","7tk-WZSqIGQ","JmTNX9wGyy9_1ax5wrdbDg","ARTHUR CHRISTMAS (2011)","Operación Regalo","","P3L02"), 
          pa("AvzZIqFrLM93oJ4c8eG6v6kX6YNMLwXz","Fq358xHbzN4","iPRQuknIdHisc24r6xnSPA","AS ABOVE SO BELOW","Asi En La Tierra Como En El Infierno (2014)","","P3L02"), 
          pa("LZsheIta2gy9L7WQepIxXICCCH0ZGwlv","4vXnH6wahcA","w11wVK9UPz8ia5FmRV-EQQ","ASH & DUST","En La Mira De Los Asesinos (2022)","","P3L02"),
          pa("T6duW-ZlkvuICRwKP78SbmFsuIfQ5du-","u9zJBBUZ9Fo","pWxSsrr6RDAW2weWdKT2vg","ASI ES MI TIERRA","Así Es Mi Tierra (1937)","","P3L01G"), 
          pa("7WdQTW9iaPUZCx4Q9N0-MKmAadcP-i7y","FvfVh7a3UgE","IYwR5Az2weSeeEH33RVOAg","ASSASSINATION NATION","Nacion Asesina (2018)","","P3L01"), 
          pa("c8xy4hCee-sp3UgGdjMH5xOy4T__oBCs","N1lytCgJagI","65fepHQVbDCI8oUL9-sUbw","ATHENA","Atena (2023)","","peroiz#g"), 
          pa("bL4IQfmeATkLCSUTjhdBFm_E1SXY6Ed5","r39ys9K3LgA","2nNnFJqXJYeZ4k1ES42z9g","ATLANTIS THE LOST EMPIRE","Atlantis El Imperio Perdido (2001)","","P3L01"), 
          pa("2Fcg6xHM_aNCS5tVDOp8JraweKVzH2a9","JEOZc3R3Ej4","8jZcXU9maXBvpsAffcXG3A","ATLANTIS MILO\'S RETURN","Atlantis El Regreso De Milo (2003)","","P3L01"),
          pa("5m7AToUGdJZ8KIehm0HC4C-Wp_4UxgLQ","AI3r_sUe2iI","2Ari6xOvQW-bisWzDUxFww","ATRAVES DE TU MIRADA","Atraves De Tu Mirada","","P2"),
          pa("24DwjtYGrTrlH_W5UKfgTbyVEWm815nZ","cq0m15Sip0g","L0-7Cfl-YdYGdP_1mhqUUg","ATRAVES DEL MAR","Através Del Mar (2023)","","P1"),
          pa("J1VMIEQmj4nTaZRo2aYXIdlZV8cPrRKF","XROEPkzyCRg","FBwtj4ASh2tpj_nC3V4pQQ","AUSTIN POWERS GOLD MEMBER","Austin Powers En Goldmember (2002)","","P3L01"), 
          pa("0D-ARQzXxr3tu8fI-T338Chd1Aw12SG6","TESYD2hkt5M","Sp3MpMsJIf2gGXIMwYoZnw","AUSTIN POWERS INTERNATIONAL MAN MISTERY","Austin Powers El Super Agente (1997)","","P3L01"), 
          pa("blQ9WKobl2JtmsByRmJQolazTCi0nCeP","_vJdXx-w0Ug","EDzaUGdOL8URyZ1abCoZuA","AUSTIN POWERS THE SPY WHO SHAGGED ME","Austin Powers El Espía Seductor (1999)","","P3L01"), 
          pa("T4nDCG2ww4nw8ExGxuf4tvUc7K6qKPFL","5PSNL1qE6VY","vB6tPpyv2iBm0rpz5oQEbw","AVATAR","Avatar (2009)","","P3L01"), 
          pa("C-w72upFJKfrwPqQnxQuaahZm76NGJvi","d9MyW72ELq0","8cPK68YoSkk5dfZPAaLSxQ","AVATAR THE WAY OF WATER","Avatar El Camino Del Agua (2022)","","P3L01"), 
          pa("ZnYguh4Pf7tvuM4lAYClN4xHSRgTg6Qn","ByAn8DF8Ykk","HZFWdAq1BTjFx_bIxaTF0g","AVATAR THE LAST AIRBENDER","Avatar La leyenda de Aang (2024) (1T8E)","1 Temporada 8 Episodios","P3L01G"),
          pa("YVQ0KT5tGDO5Bwmb59q8o2dOtz6F_rGH","T0-uoVFBtv0","6QDcfywIWfs0tuCWFyLv0Q","THE AVENGERS,","Los Vengadores (2012)","","the avengers, avengers age of ultron, avengers infinity war, avengers end game, P3L01"), 
          pa("Lje4Z8XWkeQBJZuqBI0JZRSbYR3K2emh","DMFBm_lp4rU","LQcdXKz_WBBYD7e-gBhcog","AVENGERS AGE OF ULTRON","Vengadores La Era De Ultrón (2015)","","the avengers, avengers age of ultron, avengers infinity war, avengers end game, P3L01"), 
         pa("ssa3Ra85zKahHh8XRq2gNU-ILHpn3DEs","6ZfuNTqbHE8","SP3Zv4zGYVE7Fb9W8-29ag","AVENGERS INFINITY WAR","Vengadores Infinity War (2018)","","the avengers, avengers age of ultron, avengers infinity war, avengers end game, peroiz#g"),
         pa("Z5lIcnqNypHTSa00kOET7z-aoLZypOC8","TcMBFSGVi1c","6KcHET5-POpS3oRCBrLvTA","AVENGERS END GAME","Vengadores Endgame (2019)","","the avengers, avengers age of ultron, avengers infinity war, avengers end game, P3L01"), 
          
     
     
     ] }
];