const data_peliculasR= [
     { id: 'PelículasR', data: [
          { id: '1vjSSvXlfiwJNxdm4GZR75scoR-5AUMth', youtubeId: 'k-OOfW6wWyQ', buttonId: '1arBiNzgI274-lBs2eG-d5w', title: 'RANGO', subtitle: 'Rango (2011)', buscar: 'P3L02' },
          { id: '1a8Gq2mgoMQ2Ff1CSsabVgO4pLMRDeQnN', youtubeId: 'pZ3qsLzssKI', buttonId: '1L1HNPNgKqnE4WdSgsaHucw', title: 'RANMA ½', subtitle: 'Ranma ½ (1989-92)', subtitle2: '7 Temporadas 161 Episodios 13 OVAS', buscar: 'S3R01' },
          { id: '1CAFLMiGvbwRBAF3tO3trjq9bL5h_umAa', youtubeId: 'fzUsEmotXMs', buttonId: '1qgI3AisUfW9h5p2QX4hXFg', title: 'RANMA ½ THE MOVIE, BIG TROUBLE IN NEKONRON CHINA', subtitle: 'Gran Aventura En Nekonron China (1991)', buscar: 'Japón, S3R01, Peliculas Animadas, Animes' }, 
           { id: '1a9eTYS7jEgabmYu5NFLMJO5pVq7DNkGX', youtubeId: '9VmX0_w3CY4', buttonId: '1sQOgKuGTM-sisQO-EsfUxg', title: 'RANMA ½ THE MOVIE 2, NIHAO MY CONCUBINE', subtitle: '¡Ni Hao, Mi Concubina! (1992)', buscar: 'S3R01' }, 
           { id: '1vQ1T3LaWKBO6NURxM2QHpjb3Uy48eCH8', youtubeId: '2CRjdwRYQbU', buttonId: '1GDvYLVsvh_lrQZB_sbbfbw', title: 'RAMBO', subtitle: 'Rambo IV (2008)', buscar: 'First Blood, P3L01' }, 
           { id: '1j-nZ46R0OYNVa3ige2sBGlZ4LFsFsoFb', youtubeId: 'jtPNhGWxY4g', buttonId: '1UCdwEQZYd12_5vVoAG8rjw', title: 'RAMBO FIRST BLOOD PART II', subtitle: 'Rambo II (1985)', buscar: 'P3L01' }, 
           { id: '1Hw7enUqd9tdJhVAbEsQkao8g34Rz0UO9', youtubeId: 'Xt972U5z77w', buttonId: '1WUYyZJwst9YlyMFKuLc3Dg', title: 'RAMBO III', subtitle: 'Rambo III (1988)', buscar: ' First Blood, P3L01' }, 
           { id: '1hVt51RwLJ0vMWydvYXWlJwhiCV-S6VtF', youtubeId: 'vDQMo32Uomw', buttonId: '14h4DMLsxWq3_YFfz5NuBoA', title: 'RAMBO LAST BLOOD', subtitle: 'Rambo Last Blood (2019)', buscar: 'First Blood, P3L01' }, 
           { id: '1ZCd_8IqlkaIaCP13vorZ_1Jmzz0a4Drr', youtubeId: 'mebIhXK8srA', buttonId: '1q2otmf5sgjcZbOsD71Z5rQ', title: 'RANSOM', subtitle: 'Rescate (1996)', buscar: 'P3L01' }, 
           { id: '1MWQOAUcSR-jTSevz_RiK2Zp8eyIuQPc3', youtubeId: 'BAVITOn-Usk', buttonId: '12NFjEanCTjOXa2d6eXbW6Q', title: 'RED', subtitle: 'Red (2010)', buscar: 'P3L01' }, 
           { id: '1CrmLqSRqcRQDQUwgymbxEgF5H_NWNhUI', youtubeId: 'ZfB8QwYBPxY', buttonId: '1vqVoZsl7NlC7zCHkR0aeTQ', title: 'RED 2', subtitle: 'Red 2 (2013)', buscar: 'P3L01' }, 
           { id: '1OzGhACbcme9ljAfd1iymijoe37XezRIX', youtubeId: 'yzQYokimcg0', buttonId: '1n7uQ0VJcXbA2TVG-raZK2g', title: 'REIGN OVER ME', subtitle: 'La Esperanza Vive En Mí (2007)', buscar: 'P3L01' }, 
           { id: '10GriI-JKRp4BI_rc3FaIdG7pf7T8A043', youtubeId: 'To87iNMhedU', buttonId: '1hVHKdirq1Kj-bEabJmUD-g', title: 'RELATIONSHIP GOALS', subtitle: 'La Meta Es El Amor(2026)', buscar: 'peroiz#g' }, 
           { id: '1RPpMFDPnILnuh-zF8XEq6GY1bbFd8t9L', youtubeId: 'NcKWCVb7f6Y', buttonId: '1Qy4X_cR_hxC9s8kg8e4_sw', title: 'RÉMI NOBODY\'S BOY', subtitle: 'Remi El Niño De Nadie (2018)', buscar: 'P3L01G' }, 
           { id: '1jRIT7kbv-H5GU7HEnRDC81VyCjRsJz3c', youtubeId: 'JAHKQPBKSZ8', buttonId: '1_W-_AEoPx2usXOl7j_bwFw', title: 'REPLICAS', subtitle: 'Replicas (2018)', buscar: 'P3L01' }, 
           { id: '1kOJ0lzkQzQkBRp7mwMpXDcOrcIPqcCc6', youtubeId: 'HhBAIDHvRTc', buttonId: '1CBbsQwVJS9X4MC1QatawAw', title: 'RESIDENT EVIL', subtitle: 'Resident Evil: El Huésped Maldito (2002)', buscar: 'P3L02' }, 
           { id: '1CZnWpTPV4XgTE9PK_RAOpDqXJv4NUwdy', youtubeId: 'Lhzu-BlANWY', buttonId: '1zqcP2LBszHYD2ALEPNirmA', title: 'RESIDENT EVIL AFTERLIFE', subtitle: 'Resident Evil 4: La Resurrección (2010)', buscar: 'P3L02' }, 
           { id: '1Yxo-gRB0NDB1xECcy0YWMKZDBCsxftC3', youtubeId: 'nzF3yoF7N_E', buttonId: '1-EsjMQdJVnUSCjxx5TpaJA', title: 'RESIDENT EVIL: APOCALYPSE', subtitle: 'Resident Evil 2: Apocalipsis (2004)', buscar: 'P3L02' }, 
           { id: '13aLFmbZI8HwYKqdMYNXJgWdKCTBJgOB8', youtubeId: 'MNK1qT7RGvc', buttonId: '1l-BcGqdzYoFDl-xS9goaaA', title: 'RESIDENT EVIL: DAMNATION', subtitle: 'Resident Evil: La Maldición (2012)', buscar: 'P3L02' }, 
           { id: '1rGEdrR3bnd11QfcsvbP69v5ch72LE9sn', youtubeId: 'L-vkuA8oqMY', buttonId: '1Ux-n8L695Nq1RUzBvd7qqQ', title: 'RESIDENT EVIL: DEATH ISLAND', subtitle: 'Resident Evil: Isla De La Muerte (2023)', buscar: 'P3L02' }, 
           { id: '19PcIbljowGm6DnoICj-Qsgl8KFPeKHpA', youtubeId: 'bbfIAiCwfwc', buttonId: '18qdLr0OOD7QkdJQXKkmHLg', title: 'RESIDENT EVIL: DEGENERATION', subtitle: 'Resident Evil: Degeneración (2008)', buscar: 'P3L02' }, 
           { id: '13-RL1E7qhMGKtt0wIoWD6TD7Hb5cdTwy', youtubeId: 'lLn0t7m0gO8', buttonId: '1btE2W3kgVSid3LRnSFjJ6g', title: 'RESIDENT EVIL: EXTINCTION', subtitle: 'Resident Evil 3: Extinción (2007)', buscar: 'P3L02' }, 
           { id: '1sudV68HplQkA8x_vbgdma5FfU2CGkBTW', youtubeId: 'P-js-Eww1OI', buttonId: '1hUyCdJm44YbHQkPaYOwpoQ', title: 'RESIDENT EVIL INFINITE DARKNESS', subtitle: 'Resident Evil Oscuridad Infinita (2021)', subtitle2: '1 Temporada 4 Episodios', buscar: 'BUSCAR' }, 
           { id: '1W8D6olDlC7Ufz7DijnknCTjSCPzLxiYr', youtubeId: 'hoyMT-7wEqs', buttonId: '1uMU4g6VESOkkRjQE-h2SyA', title: 'RESIDENT EVIL: RETRIBUTION', subtitle: 'Resident Evil 5: La Venganza (2012)', buscar: 'P3L02' }, 
           { id: '19OD4nXVOIfa0hVeY7pyeHCTTs1s0wZSU', youtubeId: '79Sd4GtOXuI', buttonId: '1nuFfhnQ93bZGxOHhB_P_dQ', title: 'RESIDENT EVIL: THE FINAL CHAPTER', subtitle: 'Resident Evil: Capítulo Final (2016)', buscar: 'P3L02' }, 
           { id: '1yo3iqpms-IxDlQtQN1pQLRSa-JW9cH83', youtubeId: 'Uw2Styd2RAU', buttonId: '1BvKktFX7Lb6QrUxYpeQyng', title: 'RESIDENT EVIL: VENDETTA', subtitle: 'Resident Evil: Venganza (2017)', buscar: 'P3L02' }, 
           { id: '1w-LSzlfiz_wyf-oRt381uQYwvSWa2p3k', youtubeId: '4q6UGCyHZCI', buttonId: '1Wgl4rtoLBh-AW5DafOu30Q', title: 'RESIDENT EVIL: WELCOME TO RACCOON CITY', subtitle: 'Resident Evil: Bienvenidos a Raccoon City (2021)', buscar: 'P3L02' }, 
           { id: '1LWqQ_dY4PhO2MGfIr_gbuJek6vRWDvFF', youtubeId: 'IuhgTsDtYK0', buttonId: '12upN056dWcelYl7FZWttsQ', title: 'REVOLT', subtitle: 'Revuelta (2017)', buscar: 'P3L01' }, 
           { id: '1dC0C3laVmcLe-TbzTn4u3iR366v_y4hX', youtubeId: 'zpngGG1ayZ0', buttonId: '19MknIH0XgoL8wP-g7rcUSw', title: 'RISE OF THE GUARDIANS', subtitle: 'El Origen De Los Guardianes (2012)', buscar: 'P3L01' }, 
           { id: '1V9RQGASmRcDrwTmetLObkjK3F-u2grsf', youtubeId: 'Rwp58drJh2A', buttonId: '1iULHb1P2mI_J1MYU1dH52Q', title: 'RISE OF THE PLANET OF THE APES', subtitle: 'El Origen Del Planeta De Los Simios (2011)', buscar: 'P3L01' }, 
           { id: '1E-KsXP_NBIlP7H33d0WkRIxIpw-iv2s4', youtubeId: 'VExbETiGRJc', buttonId: '1b2byN_aQWcxOiDwTNIpTgw', title: 'ROBOTECH', subtitle: 'Robotech (1985)', subtitle2: '3 Temporadas 85 Episodios', buscar: 'P3L00' }, 
           { id: '1sgwi4H8-jY25lQttyQ_u6HrTLSEhcKXC', youtubeId: 'EV21xnqOPFA', buttonId: '1rLRtbH5Zx7pcd2iAQlxosA', title: 'ROBOTECH THE SHADOW CHRONICLES', subtitle: 'Robotech Crónicas Sombra (2006)', buscar: 'BUSCAR' }, 
           { id: '1_QvAo2qcN1oL2wpBrlx7elbS2_u2DZ-L', youtubeId: 'LVL2LDf1bcU', buttonId: '1s29K5PBxCe9wOkElRqkSag', title: 'ROCKO\'S MODERN LIFE', subtitle: 'La Vida Moderna De Rocko (1993-96)', subtitle2: '4 Temporadas 52 Episodios', buscar: 'P3L01G' }, 
           { id: '1UOGcxCvbGrqgCqgV0H12YyINqCIKfbF9', youtubeId: '1Now4KeAiys', buttonId: '1bFuLx-iAd8ohkXfatfyAYA', title: 'ROCKO\'S MODERN LIFE STATIC CLING', subtitle: 'La Vida Moderna de Rocko Estática (2019)', buscar: 'P3L01G' }, 
           { id: '1hC3XxSl72dZPLp9cCQNtabypCY_mNWzj', youtubeId: '-Hk-LYcavrw', buttonId: '1V9kgBdWsjfzXt0t8p202tA', title: 'ROCKY', subtitle: 'Rocky (1976)', buscar: 'P3L01' }, 
           { id: '1JPSli_6yFJvLz7U-7k2YfQFY-T8twdJH', youtubeId: '8tab8fK2_3w', buttonId: '1cdzaBswOO5ccc-uzyibxRQ', title: 'ROCKY BALBOA', subtitle: 'Rocky Balboa (2006)', buscar: 'P3L01' }, 
           { id: '1z30_OgCNm5xmHugnu3f6K7EiYMa6QBND', youtubeId: 'A2P9ATb9Qx8', buttonId: '1wmmjLfkuvoIJI93Q01sWkA', title: 'ROCKY II', subtitle: 'Rocky II (1979)', buscar: 'P3L01' }, { 
						    	id: '1yegqHQH6kN9KbyDXuTGWwDOsS8ETOwcA', youtubeId: 'o7vbDPUMWDc', buttonId: '18s4NBEF9frHX_BRADTorMg', title: 'ROCKY III', subtitle: 'Rocky III (1982)', buscar: 'P3L01' }, { 
						    	id: '1A7OH0GyXay3HI2vLOoyMzT_nWmSWEz2y', youtubeId: '4qjV0bB2V0Q', buttonId: '1I9hr3e6anyZXrVOqwVvhww', title: 'ROCKY IV', subtitle: 'Rocky (1985)', buscar: 'P3L01' }, 
           { id: '1Pbg8rI_XojURJUwdb1gyClOXCdPaz2pF', youtubeId: 'C2_k8p3RQx4', buttonId: '1JSIKRuWMfE49I4YqsgchuA', title: 'ROCKY V', subtitle: 'Rocky V (1990)', buscar: 'P3L01' }, 
           { id: '1iF7ZF4ktYMzetsRWRG_ErMikyiCb8fQ5', youtubeId: 'frdj1zb9sMY', buttonId: '19ItYyZAdbwaeC0e6sR2_Rw', title: 'ROGUE ONE A STAR WARS STORY', subtitle: 'Rogue One Una Historia De Star Wars (2016)', buscar: 'La Guerra De Las Galaxias, Andor, P3L01G' }, 
           { id: '1wKc8Mfh2dGFMA7mxijUrQPguAgkWoPsM', youtubeId: 'sKVYRtE-kXI', buttonId: '1WZlIJjFmaZMYx2FJfpGC6Q', title: 'ROMA', subtitle: 'Roma (2018)', buscar: 'P3L01' }, 
           { id: '18JW06vyvGzMgZIig-r1AZ4dvoRsqFFqd', youtubeId: 'uTSH3AW992I', buttonId: '1I2BxjX-l6zeJ8-MJ8oqdUA', title: 'ROMEO Y JULIETA', subtitle: 'Romeo y Julieta (1943)', buscar: 'P3L01G' }, 
           { id: '1KN4SSbzllxXxIMT-5tQBBssVj0bVs337', youtubeId: 'qKIpzkoAqC0', buttonId: '1KHlhj8Fu0HL8xvB2k2L4RQ', title: 'RONIN WARRIORS', subtitle: 'Los Guerreros Samurái (1988)', subtitle2: '1 Temporada 39 Episodios', buscar: 'S3R01' }, 
           { id: '1_ua00YwuKaOEdjKnKz9NLKpHwkSiHLou', youtubeId: 'iAMKwDsfUeU', buttonId: '1sW_LoEn_RO2hHnhTwIYNNw', title: 'RUBY GILLMAN TEENAGE KRAKEN', subtitle: 'Krakens y Sirenas Conoce a Los Gillman (2023)', buscar: 'P3L01' }, 
           { id: '1yeIeNq9baxQgAduyO5VsBChWAXvPvZL2', youtubeId: 'GQBTpBSWFUE', buttonId: '1Mm2gC5Nqt2vMNGPdg0UKLw', title: 'RUMBLE IN HONG KONG', subtitle: 'El Joven Tigre (1973)', subtitle2: 'Chino Sub: Español', buscar: 'P3L01' }, 
           { id: '1nhQxoRsU8ZPH35M-x9EtRgbr-_VtWgIV', youtubeId: 'f8cFqHeUVMs', buttonId: '1QGj2C35DKW6JiV8-NOV2iw', title: 'RUROUNI KENSHIN', subtitle: 'Samurai X (2012)', buscar: 'P3L01' }, 
           { id: '1zdC9rimEKMIYMOxEt13RpdcKgmMpkikU', youtubeId: '_fmj3oqsIro', buttonId: '1udCLJpiNL0G7DyHTm0C7Ng', title: 'RUROUNI KENSHIN KYOTO INFERNO', subtitle: 'Samurai X Infierno En Kyoto (2014)', buscar: 'PRL01' }, 
           { id: '1zuWaNDEV8EDzcYLz_YKuy17oEDNCX-7T', youtubeId: 'xXtG2Ck526U', buttonId: '1IGm-NrV85Y6zkYZfkz3qTw', title: 'RUROUNI KENSHIN THE BEGINNING', subtitle: 'Samurai X El Origen (2021)', buscar: 'P3L01' }, 
           { id: '1VSCOY01QiC95WJMT8nuuqAP6b5KaF60a', youtubeId: 'ndUd5eZ4dGU', buttonId: '1R-WRaxQNsjL5zII_YPydFw', title: 'RUROUNI KENSHIN THE FINAL', subtitle: 'Samurai X El Final (2021)', buscar: 'P3L01' }, 
           { id: '1nf_04O-ZobUh42eIHyC51M3OpiNefb1f', youtubeId: 'Zdg2c5Uqu_c', buttonId: '1lSS92yHP3VNKvwi9taDhog', title: 'RUROUNI KENSHIN THE LEGEND ENDS', subtitle: 'Samurai X La Leyenda Termina (2014)', buscar: 'P3L01' }, 
           { id: '1TbngwafsFR2I9A6eIs2UgIow-Lr-UNdG', youtubeId: 'JMiFsFQcFLE', buttonId: '1Z9hwk7CV58QTrKCeiTuS4Q', title: 'RUSH HOUR', subtitle: 'Una Pareja Explosiva (1998)', buscar: 'P3L01' }, 
           { id: '1u3VmAtv70yS7wONFZkH56c1VH7gw5mSv', youtubeId: 'SCTzYY95Aw4', buttonId: '1FOqD4iLSi-EmStNnCd8-sg', title: 'RUSH HOUR 2', subtitle: 'Una Pareja Explosiva 2 (2001)', buscar: 'P3L01' }, 
           { id: '1L53hxR6t1bqa-5Q_6q4pAO1mpVaC_Egm', youtubeId: 'FRDRWXfQyJE', buttonId: '1Lm_1yJ1LCoAT8ny08KoGoQ', title: 'RUSH HOUR 3', subtitle: 'Una Pareja Explosiva 3 (2007)', buscar: 'P3L01' },
            

            // ... TODOS los demás elementos de este carrusel
        ]
    }
];