const data_peliculasP= [
     { id: 'PelículasP', data: [
          { id: '1Rq8M0VyuIkzCa9wQZvPDf35oSTrzU5NC', youtubeId: '8jVuOheTNGQ', buttonId: '1zde4jq1pP-CFaIFNDx6pkw', title: 'PALMER', subtitle: 'Palmer (2021)', buscar: 'P3L01G' }, 
           { id: '1ajAR1hukWi9IAWJDZ2jYwF7PXk8DAVz0', youtubeId: 'C2E9pQ4hh0s', buttonId: '1iP77JXD2SAvGREuU-3V6gQ', title: 'PANCHO VILLA EL CENTAURO DEL NORTE', subtitle: 'Pancho Villa El Centauro Del Norte (2023)', subtitle2: '1 Temporada 10 Episodios', buscar: 'P3L01G' }, 
           { id: '1GaKPHwuaourNgdreqY1tBH16nVyh6ukW', youtubeId: 'h5zs9bg7jCo', buttonId: '1mEKhIMolsSCbmUGJiVZ0Kg', title: 'PARAÍSO BLANCO', subtitle: 'Paraíso Blanco (2023-24)', subtitle2: '2 Temporadas 30 Episodios', buscar: 'S3R01G' }, 
           { id: '1FjJYeJHLRn3CWJt445JVt6CZi52vrmKu', youtubeId: 'tSkLHvlOzvM', buttonId: '1fiPnZHOPM6rwCkGz-cjz0A', title: 'PAULETTE', subtitle: 'Paulette (2012)', buscar: 'P3L01' }, 
           { id: '19bjJjkh7-_fDnTODXiUpaFfrOEVp9hAi', youtubeId: 'UDgjJ9XzgHk', buttonId: '1XnS4suQt3N1v9mbcdiH6rw', title: 'PAW PATROL THE MIGHTY MOVIE', subtitle: 'Paw Patrol: La Súper Película (2023)', buscar: 'P3L01' }, 
           { id: '1dAUo38AjG6pmRBwsvsYKAPXkq5vEh59y', youtubeId: 'OTjS8SVy0e0', buttonId: '1Fv0Z7Pb1pM-RMD8r3hK2mQ', title: 'PEEPING TOM', subtitle: 'El Fotógrafo Del Pánico (1960)', subtitle2: 'Español', buscar: 'S3R01' }, 
           { id: '1SDPyb3pIUuZbE_GYvfjDKIxXJdObXqIk', youtubeId: '9lGVN9zCw1U', buttonId: '1ImNFKLVIyTgwWukdK6U9SA', title: 'PEPE', subtitle: 'Pepe (1960)', subtitle2: 'Inglés sub: Español', buscar: 'P3L01G' }, 
           { id: '1Ymrviz7MeijIf50HWGwK6pdpiRiNNyzs', youtubeId: 'sdL70wkf_H0', buttonId: '15ftsMJAZ4j6YN8JOileUQQ', title: 'PEPPERMINT', subtitle: 'Matar o Morir (2018)', buscar: 'P3L01' }, 
           { id: '123T6SoFE_4j7FrIDwVWd33yBX5f2IUxz', youtubeId: 'OP1RvkrIsWo', buttonId: '1Y9Be2O3Y9SlZqNOzW3BYcw', title: 'PET SEMATARY', subtitle: 'Cementerio De Mascotas (1989)', buscar: 'P3L01' }, 
           { id: '1R35L45sa3YKJEOnEnWqH4g2-odhsygA2', youtubeId: 'VllcgXSIJkE', buttonId: '1J6Rqr8NZAGa01xVMYUW37A', title: 'PET SEMATARY', subtitle: 'Cementerio De Mascotas (2019)', buscar: 'P3L01' }, 
           { id: '1c57NlsU-z6m3VBXXg6stAk6WA3IBdqHy', youtubeId: 'yJkBRzSgBEY', buttonId: '15AsUgGtke48VRcGZbHyLlA', title: 'PET SEMATARY BLOODLINES', subtitle: 'Cementerio De Mascotas El Origen (2023)', buscar: 'P3L01' }, 
           { id: '1I6DtucwgPWKYAIZ-KWAsEAa52Lp4v9wl', youtubeId: 'hdn56hGq5O0', buttonId: '1Utqf4m569GVwyQJfQkf80Q', title: 'PET SEMATARY TWO', subtitle: 'Cementerio De Mascotas 2 (1992)', buscar: 'P3L01' }, 
           { id: '1sC4vbqdak-bpDtyiprA5gPHOSn7frHda', youtubeId: 'BL6M27fz_d0', buttonId: '1qOtN2NXz9owvZyrft6xNDQ', title: 'PETER PAN\'S NEVERLAND NIGHTMARE', subtitle: 'La pesadilla De Peter Pan (2025)', buscar: 'P3L02' },
           { id: '1Mxx-9SUaIgya7yPKEUg2lmv2PoUle0e2', youtubeId: 'aA5bqeg-Yv0', buttonId: '1oT3_9cGHxLT1SwCsDjcOIQ', title: 'PHINEAS AND FERB', subtitle: 'Phineas y Ferb (2007)', subtitle2: 'TEMPORADA 1', buscar: 'peroiz#g' },
           { id: '13T9wDd2_Hoc9pLYgIRXWIqztRN-E0jr8', youtubeId: 'aA5bqeg-Yv0', buttonId: '1I8jBdFO-Uuetxpk8Hp0nJg', title: 'PHINEAS AND FERB', subtitle: 'Phineas y Ferb (2009)', subtitle2: 'TEMPORADA 2', buscar: 'peroiz#g' },
           { id: '1LQJQedf5ktwWZ6Bn_ZqB0gq2XeQyyHZY', youtubeId: 'UccudZUwSn8', buttonId: '1pJhl9boog4Rd3RmT84XHrg', title: 'PHINEAS AND FERB STAR WARS', subtitle: 'Phineas y Ferb La Guerra De Las Galaxias (2014)', buscar: 'peroiz#g' },   
           { id: '11RmdRYjpRIiNDQo_sa_7uCkHDmUCJj8i', youtubeId: 'jwfNAPIfip4', buttonId: '16vyxZW245z7qtu7XvttmZA', title: 'PHINEAS AND FERB THE MOVIE: ACROSS THE 2ND DIMENSION', subtitle: 'Phineas y Ferb a Traves De La 2da Dimension (2011)', buscar: 'peroiz#g' }, 
           { id: '1nAIVX0YvsbjD6xMGD9pj4mQOUOTHWyUG', youtubeId: 'cuG-Typdck0', buttonId: '1FDq0fVzdgiG_oTyeLpJGVg', title: 'PHINEAS AND FERB THE MOVIE: CANDACE AGAINST THE UNIVERSE', subtitle: 'Phineas y Ferb, la película: Candace contra el universo (2020)', buscar: 'peroiz#g' }, 
           { id: '1GQdr3z4D6CQ5Pg16h1PUZIs8VcSa3ktG', youtubeId: 'vG89ig5P4g0', buttonId: '1Va2yelaAvBG1OcUFLktJHA', title: 'PÍDEME LO QUE QUIERAS', subtitle: 'Pídeme Lo Que Quieras (2024)', subtitle2: 'Español Sub: Chino Vietnamita Inglés', buscar: 'P3L01G' }, 
           { id: '13jNP5hMHWRCvGI5LG1yKTVZ5aPD3Lfhj', youtubeId: 'Rfhqw7-6uFY', buttonId: '1RR6YHn49W2lEvfeyhBaYGg', title: 'PINOCCHIO', subtitle: 'Pinocho (1940)', buscar: 'P3L01G' }, 
           { id: '10LQU8ZRinWmd7NqVluHHrSy04YIzdSjG', youtubeId: 'HKSZtp_OGHY', buttonId: '1Cg66cW4M4K-Wbbj7Rk4U7Q', title: 'PIRATES OF THE CARIBBEAN AT WORLD\'S END', subtitle: 'Pirátas del Caribe: En el fin del mundo (2007)', buscar: 'P3L02' }, 
           { id: '1qhgwR1Tdr_2VzP3hjPZlSQGtJkQxOJgH', youtubeId: 'mT2-x5Pk8WU', buttonId: '1OWh-XpxIbQss5CLOsPBraQ', title: 'PIRATES OF THE CARIBBEAN DEAD MEN TELL NO TALES', subtitle: 'Pirátas del Caribe: La Venganza de Salazar (2017)', buscar: 'P3L02' }, 
           { id: '16TuVxVAK2f1TKUafkCRUBScDr0WMLuaU', youtubeId: 'SNA-Ezahmok', buttonId: '12uJxvWFcFNJvcZhqge8fBw', title: 'PIRATES OF THE CARIBBEAN: DEAD MAN\'S CHEST', subtitle: 'Pirátas del Caribe: El Cofre De La Muerte (2006)', buscar: 'P3L02' }, 
           { id: '1A9Fqlys4dOeQKr4OSnE-WUpzYZ8mjQ8-', youtubeId: 't5AqJww06bw', buttonId: '1JwyFPkHi2Qbr9zB9IMLfJw', title: 'PIRATES OF THE CARIBBEAN ON STRANGER TIDES', subtitle: 'Pirátas Del Caribe Navegando en Aguas Misteriosas (2011)', buscar: 'P3L02' }, 
           { id: '12RWYHQmmE7rTIuMGG2W8H1VPC-EyZp0b', youtubeId: 'tnx35Z4nWWc', buttonId: '1ypWl-5CWAwHoZh5Me7gaLw', title: 'PIRATES OF THE CARIBBEAN: THE CURSE OF THE BLACK PEARL', subtitle: 'Pirátas del Caribe: La Maldición Del Perla Negra (2003)', buscar: 'P3L02' }, 
           { id: '1rAGp7v1e0PpGijxnMAeDkjCJvWPNIsDs', youtubeId: 'TY-u5P9pRwA', buttonId: '1RVAiMsqNKHduftWmJjCsvQ', title: 'PITCH PERFECT 2', subtitle: 'Más Notas Perfectas (2015)', buscar: 'P3L01' }, 
           { id: '1psq5i0MNCGrN2EWjWLjPoOi2WPayRuWG', youtubeId: 'U--v4EwBoGI', buttonId: '1pYRcwTmzGFGZ3XQckfnQuw', title: 'PITCH PERFECT 3', subtitle: 'La Ultima Nota (2017)', buscar: 'P3L01' }, 
           { id: '1goPc_1LIbP7_ryx8m50bjn6kZLc8F8zV', youtubeId: 'XAHprLW48no', buttonId: '1NKjNAOBge4qxPv0mU6fgMA', title: 'PIXELS', subtitle: 'Pixeles (2015)', buscar: 'P3L01' }, 
           { id: '1uG95LK-NFyyTkQLEqiYNG8GKJKITXpA1', youtubeId: 'lAOcBdujSoY', buttonId: '1XgGEA0aBLlWBDytl2dkmfg', title: 'PLAN V', subtitle: 'Plan V (2018)', buscar: 'P3L01' }, 
           { id: '1KQqG51ixEQtLqzj0bBjfCSAlm-mlTUd7', youtubeId: 'pfRyYz9VQ_g', buttonId: '1WUsBI7ZMk7plgnpCKW23pA', title: 'PLANET HULK', subtitle: 'Planeta Hulk (2010)', buscar: 'P3L01' }, 
           { id: '1vJykwh6WM56db7BUTGhk-8qRqxmYF5pP', youtubeId: 'k0-dUM_A-Cg', buttonId: '1ZIgRhaaW3WCKUcylzxIL_A', title: 'PLANET OF THE APES', subtitle: 'El Planeta De Los Simios (1968)', buscar: 'P3L01' }, 
           { id: '11iMOBy7ki9d1gARRpike9tV2bH25apw-', youtubeId: 'N9_EwsMhn2Y', buttonId: '1dCjucw5yc0WTInE3HEOJcw', title: 'PLANET OF THE APES', subtitle: 'El Planeta De Los Simios (2001)', buscar: 'P3L01' }, 
           { id: '1svIe3yw_hC5lpdRuGK3jDrw25luiVEkh', youtubeId: 'eU0WIo3lAoo', buttonId: '1rWJXGzm-133YvSaYf72lzA', title: 'PLANKTON THE MOVIE', subtitle: 'Plankton: La Película (2025)', buscar: 'Bob Esponja, SpongeBob Squarepants, P3L01G' }, 
           { id: '1oCWfddlfTTRKbkKrwJUbMV2-Rqm4XLdv', youtubeId: 'R8weLPF4qBQ', buttonId: '1EqwkyUmNz8cjUKNRXuIg1g', title: 'PLATOON', subtitle: 'Pelotón (1986)', buscar: 'P3L01' }, 
           { id: '1RhB4ZAUC9fItEubWSmODWrEdi2Z2O0HS', youtubeId: 'm5j0UaNuRm0', buttonId: '1LLL3e2GVfqMDbJexfsNC2Q', title: 'PLAY DIRTY', subtitle: 'Juego Sucio (2025)', buscar: 'peroiz#g' }, 
           { id: '1cGuWrYo2k4hsbDYfFWsRW4WfA-RJNfGa', youtubeId: 'uKRibaVzr8E', buttonId: '17rXuX-7Cnt2YvkuICLwQAg', title: 'POINT BREAK', subtitle: 'Punto De Quiebre (1991)', buscar: 'P3L01' }, 
           { id: '1BwnSDqX3UAdwwQtxlVe8iFY1oX51b10N', youtubeId: '8PGsP59Io20', buttonId: '1IeHrEsZGmJiK2tPdoprgTA', title: 'POKÉMON THE MOVIE THE POWER OF US', subtitle: 'Pokémon El Poder De Todos (2018)', buscar: 'P3L01' }, 
           { id: '1zGQBrHUoyqOi7n6AKCoBf-XwgvdM4rDL', youtubeId: '19qAfQoCtkA', buttonId: '1Y3dJV8u2yCkmWdP2ArT0QQ', title: 'POLAR', subtitle: 'Polar (2019)', buscar: 'P3L02' }, 
           { id: '1fiOa2l_GTGyxsflU5LVn6LYQ20Anh8wo', youtubeId: '9eZgEKjYJqA', buttonId: '1ZISQOOfU8_Jb3b6dcllrcA', title: 'POLTERGEIST', subtitle: 'Juegos Diabólicos (1982)', buscar: 'P3L01' }, 
           { id: '1GPNNAjNmECM6NbEAHNlwGUhbjf5RwL3u', youtubeId: 'HD2sz9RVzfM', buttonId: '137_K_ovQZhdPRHfTvunXYw', title: 'POLTERGEIST', subtitle: 'Poltergeist Juegos Diabólicos (2015)', buscar: 'P3L01' }, 
           { id: '18QKe3YVgpifxBxUhc0VHqSAhULQhY0md', youtubeId: 'zIuQ3-zsnc0', buttonId: '1b2A6MSLe5qUkw66QFq6Viw', title: 'POPE FRANCIS A MAN OF HIS WORD', subtitle: 'Papa Francisco Un Hombre De Palabra (2018)', buscar: 'Biblia Biblicas P3L01' }, 
           { id: '11p23i2HjUpRzFeyMbIOqMjdoal6MeEsQ', youtubeId: 'CGO32Zmh2YI', buttonId: '1ENfYb-HLqoWCAvOlvf3-NQ', title: 'POPEYE THE SLAYER MAN', subtitle: 'Popeye El Marino (2025)', subtitle2: 'Inglés sub: Español', buscar: 'P3L01G' }, 
           { id: '15l-sTc9Oc5uZvVM8qmE5tN53wdolm2_A', youtubeId: 'hGNV8A1ssAM', buttonId: '1Ay1bUT0EIRX9y_KiYCVdgg', title: 'POWERPUFF GIRLS Z', subtitle: 'Las Chicas Super Poderosas Z (2006)', subtitle2: 'TEMPORADA 1 - 52 Episodios', buscar: 'S1G' }, {
				
						    	id: '18JCXRf_Qa8WkEphPBD7E54ir9K9Yzr2V', youtubeId: 'Vo3FmkleTEQ', buttonId: '1ZSpxAWWgfMtYGSk6cretMA', title: 'PREDATOR', subtitle: 'Depredador (1987)', buscar: 'Prey, P3L02' }, 
           { id: '17P8Xu2OVcj3YvNv_QHQpSFY3W3NLxk_Z', youtubeId: 'pLe_1SheJms', buttonId: '1WAY9JYnQTAoGCpZi_XSNaw', title: 'PREDATOR 2', subtitle: 'Depredador 2 (1990)', buscar: 'Prey, P3L02' }, 
           { id: '1rSWEe-SANazTL7-unL3k-0m3k9SM_Oxk', youtubeId: 'cDWhePVoqoM', buttonId: '1rgerbh_373_UvOl_zLUJGw', title: 'PREDATOR: BADLANDS', subtitle: 'Depredador: Tierras Salvajes (2025)', buscar: 'Prey, P3L02' }, 
           { id: '1dISpR3I86U7VkECywjWjRsIfZt6t5Fc6', youtubeId: 'uzqYqoVoU74', buttonId: '15Hsz9M2r47S527sC-eaYUw', title: 'PREDATORS', subtitle: 'Depredadores (2010)', buscar:  'Prey, P3L02' }, 
           { id: '1JXAEZs1owyefYh0BY2iv02wb2R6l6CCU', youtubeId: 'xWlmzl2jCNs', buttonId: '1u6TaQs5tKbp4WiMgWNwnEw', title: 'PREHISTORIC PLANET', subtitle: 'Planeta Prehistórico (2022-23)', subtitle2: '2 Temporadas 10 Episodios', buscar: 'RP3L01G' }, 
           { id: '1YT0U7bLQp2R4R5_-Mx-yQSYnpQSKuKTZ', youtubeId: 'Ee-eE_mIXRo', buttonId: '157ZHyBMD_40RSXC0RYE9FA', title: 'PRESUMED INNOCENT', subtitle: 'Presunto inocente (2024)', subtitle2: '1 Temporada 8 Episodios', buscar: 'P3L01G' }, 
           { id: '1A9C4xhjNE7eMbOQSbH6QgwlH8-C_7vxA', youtubeId: 'ywbIkW_F1eI', buttonId: '1nxNFuGe93KIQqg3dd5sB6A', title: 'PRETTY STONED', subtitle: 'Pretty Stoned (2023)', buscar: 'P3L01' }, 
           { id: '1pKy8q6U8HJ2W6zVu5ixmtATQCYzdzc_8', youtubeId: '2EBAVoN8L_U', buttonId: '1_22VNReCkl9ZmelmNfGm-g', title: 'PRETTY WOMAN', subtitle: 'Mujer Bonita (1990)', buscar: 'P3L01' }, 
           { id: '1l_1MwJzBYB-gmy7qG7ToR9HhLFJ09VDu', youtubeId: 'wZ7LytagKlc', buttonId: '1zSi1zESCyHLMmW2XpRoP0A', title: 'PREY', subtitle: 'Depredador: La presa', buscar: 'Predator, P3L02' }, 
           { id: '1XZSfXiUpV3xq9oXTDOTUd6a_805nhEGr', youtubeId: '_HdOGSOu1kQ', buttonId: '1M5LC1WB9DTrbF0NLGfEbTw', title: 'PRIME TARGET', subtitle: 'Objetivo Clave (2025)', subtitle2: '1 Temporada 8 Episodios', buscar: 'P3L01G' }, 
           { id: '10ffUoHxu4R1Iyy8bddVh1z7SPXXKQTZD', youtubeId: '5UEv03g51kU', buttonId: '146LfkutAuXDxtZ4hBAUmEg', title: 'PROMETHEUS', subtitle: 'Alien Prometeo (2012)', buscar: 'Alien, P3L01' }, 
           { id: '1AUPtCk99h834i4KCB-19WgKDhsCpLfIh', youtubeId: 'KGqn5k227HY', buttonId: '18EZLoZODkMA4uI827u5YcQ', title: 'PUNCH DRUNK LOVE', subtitle: 'Embriagado De Amor (2022)', buscar: 'P3L01' }, 
           { id: '1n3jS3pj-XG2K2fPYIiGT3LLa29YMMrJV', youtubeId: 'hnpYNJh4aAQ', buttonId: '1vjk8wvZrnj_XUgerSnLBBA', title: 'PURPLE NOON', subtitle: 'A Pleno Sol (1960)', subtitle2: 'Francés sub: Español', buscar: 'P3L01G' }, 
           { id: '1LjDmNbHCjdQqjWqmMpcbt7En9wA23nyb', youtubeId: 'i62WffQuDPU', buttonId: '1xIkdwNrIrY0gGuZ53K-ORA', title: 'PUSS IN BOOTS', subtitle: 'El Gato Con Botas (2011)', buscar: 'P3L02' }, 
           { id: '1YqZ9kQZzx7_Szv_9-BXFdOqDv9ghIUeI', youtubeId: 'RqrXhwS33yc', buttonId: '1CO7YTHUpTVLwuScgzxxUaw', title: 'PUSS IN BOOTS 2 THE LAST WISH', subtitle: 'El Gato Con Botas El Ultimo Deseo (2022)', buscar: 'P3L01' }, 
            

            // ... TODOS los demás elementos de este carrusel
        ]
    }
];