const data_peliculasM= [
     { id: 'PelículasM', data: [
          { id: '18Jxn4fOMXmYBQd8C2vRt1SM2IJmAykPB', youtubeId: 'USwMAiuPsQI', buttonId: '1pE_u5bQq_-q96zLgOsmK2g', title: 'MABOROSHI', subtitle: 'Maboroshi (2023)', buscar: 'P3L02' }, 
           { id: '17zi6sMHjEXkbvV98i2vCbrFRZ6y5RsXX', youtubeId: 'orAqhC-Hp_o', buttonId: '1ZFbc0BLs0Scl0IzAAvRzjg', title: 'MADAGASCAR', subtitle: 'Madagascar (2005)', buscar: 'P3L01' }, 
           { id: '1IQpYrSvUEYSoy_ngKKYH3LT4v7PpYPEs', youtubeId: '4OlGHkp4ntg', buttonId: '1Jjj41JN_9N2PO9INq9j6ow', title: 'MAJOR LEAGUE SOCCER', subtitle: 'Más allá de la cancha (2025) [Ing T+Esp]', subtitle2: '1 Temporada 8 Episodios', buscar: 'P3L01G' }, 
           { id: '1HRmQCQEAp6UKR9X-OY7WgOMf6ntOPBeY', youtubeId: 'n2jOf_Rwpek', buttonId: '1OwNArgMhiK4mpqRR7M74Sw', title: 'MALCOLM IN THE MIDDLE', subtitle: 'Malcolm el de en medio (2000)', subtitle2: '7 Temporadas 151 Episodios', buscar: 'S3R01' }, 
           { id: '1jufTKlAQp9kdFie9BUtwryz-x83DJmXc', youtubeId: 'hRKVxT4-1wM', buttonId: '1s9tZr5G5aYcBLUZGp1MQ8g', title: 'MANDY', subtitle: 'Mandy (2018)', buscar: 'P3L01' }, 
           { id: '1QQaJWiiv0av-V421KSvw2H4jsyyfByL8', youtubeId: '-XbId5P9q_M', buttonId: '1d7BbU5l6eGHGSKop2CdaTA', title: 'MANIAC COP', subtitle: 'Maniac Cop (1988) [Esp-Ing T+Esp-Ing]', buscar: 'P3L01G' }, 
           { id: '1Hb48a81n4l5zcK8jFDZ-wePS_uw0R-I6', youtubeId: 'ZlgD7JEwAME', buttonId: '1ysyqafFy61dfK2sUl7lRkA', title: 'MARCIANOS VS. MXICANOS', subtitle: 'Marcianos Vs Mexicanos (2018).', buscar: 'P3L02' }, 
           { id: '1sFu5Vnl_Ym9AJXJp-MrqgePE_UR7vCmv', youtubeId: 'jwtlgpBecvY', buttonId: '1961zOe4O95MOesDs4tq3DA', title: 'MARVEL STUDIOS LEGENDS', subtitle: 'Leyendas De Marvel Studios (2021-23) (2T46E)', subtitle2: '2 Temporadas 46 Episodios', buscar: 'P3L01G' }, 
           { id: '1GWMgBcSYpvjAwpqaO03tgFXz0aUpE2hZ', youtubeId: 'kvt41MIelDE', buttonId: '1t6y2qzhsF7jw7WRloN3LQg', title: 'MARY POPPINS RETURNS', subtitle: 'El Regreso De Mary Poppins (2018)', buscar: 'P3L01' }, 
           { id: '1mJ-3cvEN8hBMAH4m6o_Yn8JJE01qU3uH', youtubeId: 'T5l8cvuo7IA', buttonId: '1J-LgbTCC8zsvGOrtUOmedQ', title: 'MARY QUEEN OF SCOTS', subtitle: 'Las Dos Reinas (2018)', buscar: 'P3L01' }, 
           { id: '1iHIflUsbgnO5s2f7xWPrdCXO0NUiCRoq', youtubeId: 'K8sTWV1mwzg', buttonId: '1Jsa2kQSxHW9VVtFzKTZjrQ', title: 'MATANDO CABOS', subtitle: 'Matando Cabos (2004)', buscar: 'P3L01' }, 
           { id: '1liG8dUfAo-QnAj2q8iYwwCkBHkmzQIyz', youtubeId: '_iq1E8jLCm4', buttonId: '1OKxyJ2h3UnYgPErr-jArgg', title: 'MATANDO CABOS 2 LA MASCARA DEL MASCARA', subtitle: 'Matando Cabos 2 La Máscara Del Máscara (2021)', buscar: 'P3L01' }, 
           { id: '12LAHlLkub8XyCWMKUerRXrdyXVF7aLOx', youtubeId: 'RsJ05HLe7_8', buttonId: '1zCy8ggTXUqFBAFEkL0VJrw', title: 'MAZINGER Z INFINITY', subtitle: 'Mazinger Z Infinity (2017)', subtitle2: 'Japonés sub: Español', buscar: 'P3L01' }, 
           { id: '1qOCp-FXcpcigILPwampKo-uqrSoCw03S', youtubeId: '4P95AmGPFEw', buttonId: '1O1NNZeDRNl4Ec9m2lU8wIQ', title: 'MCCARTNEY 3, 2, 1', subtitle: 'McCartney (2021) [Ing T+Esp]', subtitle2: '1 Temporada 6 Episodios', buscar: 'P3L01G' }, 
           { id: '1ghNkVjp-NReZOgA5Ry6vsD4qggvNawE0', youtubeId: '6QQZvn3Oo10', buttonId: '1yoHn6HZMYwTRN338S71PUw', title: 'ME ENCONTRARÁS EN LO PROFUNDO DEL ABISMO', subtitle: 'Me Encontrarás En Lo Profundo Del Abismo (2022)', buscar: 'P3L02' }, 
           { id: '1gvUyozi4FnA6IPdn9DW_AdfmCGPwK_ry', youtubeId: 'VdaoOVrecg0', buttonId: '1FVAHdsHGA0jHBM-qm6DyVQ', title: 'MEAN GIRLS', subtitle: 'Chicas Pesadas (2024)', buscar: 'P3L02' }, 
           { id: '1FpID-wJciCVwj9d5Us5H0Zyzcw16Dsza', youtubeId: 'GTdFPPU8DGc', buttonId: '1y7PD007yfJUPFuABzphEmQ', title: 'MEGAMIND', subtitle: 'Megamente (2010)', buscar: 'P3L02' }, 
           { id: '11xDv3Z7x464NzhX9MuLmlmrp_kuhK60f', youtubeId: 'kaXb19ZkAco', buttonId: '1C8cpbqRK0qhskvhYDR1PSA', title: 'MEGAMIND VS. THE DOOM SYNDICATE', subtitle: 'Megamente Contra El Sindicato De La Perdición (2024)', buscar: 'P3L02' }, 
           { id: '10pAr8QFXG0AwxzN0sAA32BoikoQwobKf', youtubeId: 'tzuEhKs8lOM', buttonId: '19hb3NNpKZGlqHbhKkAj4Dw', title: 'MEMOIR OF A SNAIL', subtitle: 'Memorias De Un Caracol (2024)', buscar: 'P3L01G' }, 
           { id: '1ORGWzKrQELFgH8W3SW5fzLmPdxYi2Crg', youtubeId: 'yGw8yw6Mso8', buttonId: '1YUpVu64DAt8oEiRzu-yuqA', title: 'MEMORY', subtitle: 'Asesino sin memoria (2022)', buscar: 'P3ROIZ' }, 
           { id: '1ifmTaXZWJTZoTLa-ojp6LLpLFzZpMcZm', youtubeId: 'MHMqpwnUazY', buttonId: '1WedDNj_UjBiy0q3y2Ekqlg', title: 'MEN, WOMEN AND CHILDREN', subtitle: 'Hombres Mujeres y Niños (2014)', buscar: 'P3L01' }, 
           { id: '1W2ms34-F12EQ7Jdmk9k64FociLCpSCDX', youtubeId: '1GEwdzDnNps', buttonId: '1khXcxMOJZV_Rs5cmPfaPbA', title: 'METALLICA S&M', subtitle: 'San Francisco Symphony & Metallica (1999)', buscar: 'Conciertos Música P3ROIZ' }, 
           { id: '1oG2SifqQ1_T3QoDGP5lutYn0n3g8ByAr', youtubeId: '0m6smR-M2qg', buttonId: '1wY2Vp04W9_RCfoE_LSjPzw', title: 'METALLICA S&M2', subtitle: 'San Francisco Symphony & Metallica 2 (2019)', subtitle2: 'Inglés', buscar: 'Conciertos Música P3L01G' }, 
           { id: '1lQqZd00PjRsjHEQXv6n5Wc9DGhuffMtA', youtubeId: 'g9zPEy2KaPQ', buttonId: '10mn3yw1dY_rcEB5haM2xUQ', title: 'MIA AND THE WHITE LION', subtitle: 'Mía y El León Blanco (2018)', buscar: 'P3L01' }, 
           { id: '1CFT5sQrHkSMBYCm4pLUIpjNSoBfae68Y', youtubeId: 'hjS-RGoif1Q', buttonId: '1E9Pd3bLU9xX9DuaBS-SaJw', title: 'MICKEY 17', subtitle: 'Mickey 17 (2025)', buscar: 'P3L01' }, 
           { id: '1AHiyw319f58omZCsfCTR4fCzhhMLYxj_', youtubeId: 'AM5I9N1OzTc', buttonId: '1rodVVaU8EuQib861pjP2Xg', title: 'MIDNIGHT FAMILY', subtitle: 'Familia de Medianoche (2019)', buscar: 'P3L01' }, 
           { id: '1QjjwrJDuENkysfT8zvhvvSOU4YcJoKbf', youtubeId: 'AM5I9N1OzTc', buttonId: '1a6gjap_XwmNq4emoWsnzoQ', title: 'MIDNIGHT FAMILY', subtitle: 'Familia De Media Noche (2024) [Ing T+Esp]', subtitle2: '1 Temporada 10 Episodios', buscar: 'P3L01G' }, 
           { id: '14-RlNe_2MrHzKaqmX7e7WOr19e2n1qFs', youtubeId: 'l9laReRAYFk', buttonId: '1ewj9UGJsthASkm0gSuI53Q', title: 'MIDWAY', subtitle: 'Batalla En El Pacífico (2019)', buscar: 'P3L01' }, 
           { id: '1dCVqWHjnp6s7XDM_hjYMP3iPOINHXhN2', youtubeId: 'eJU6S5KOsNI', buttonId: '1xJybg5uziEXriM-siopZcg', title: 'MILE 22', subtitle: 'Milla 22 El Rescate (2018)', buscar: 'P3L01' }, 
           { id: '1abrlQBv0zrFwIfbGR9HHvqY1oQDuVZmT', youtubeId: 'L8Pbjh4EZRk', buttonId: '1Alurve131HQVoNpAz8oL6A', title: 'MISSION IMPOSSIBLE', subtitle: 'Misión Imposible (1996)', buscar: 'P3L02' }, 
           { id: '1yWo9Uuk25lhvOTf-1sxLJ0OV7i2lB4VI', youtubeId: 'HwXbmwTvoT4', buttonId: '1HBKnp-7jksxE9LwjBrXTpg', title: 'MISSION IMPOSSIBLE II', subtitle: 'Misión: Imposible 2 (2000)', buscar: 'P3L02' }, 
           { id: '1MSXewhi2kp4kt-WQPbTyOWpHR6AL70kQ', youtubeId: '4oVva0muTE8', buttonId: '1fjNiFjGeO1PmpN539-Z5xg', title: 'MISSION IMPOSSIBLE III', subtitle: 'Mision Imposible 3 (2006)', buscar: 'P3L02' }, 
           { id: '1n5GC71DBmWPNU-mKj6yWixSVMNRfpJo8', youtubeId: 'Imehr2YwCjo', buttonId: '1XrhM4TsTTpIlbmj7fdbFGA', title: 'MISSION IMPOSSIBLE DEAD RECKONING PART ONE', subtitle: 'Misión Imposible Sentencia Mortal Parte 1 (2023)', buscar: 'P3L02' }, 
           { id: '1KYyHDlmFYIghH0yKQF0wcrH1Jkx2QLlb', youtubeId: 'lB7jqyoOayU', buttonId: '10PwN-XO9EXAOmVTyg22NPA', title: 'MISSION IMPOSSIBLE FALLOUT', subtitle: 'Misión Imposible Repercusión (2018)', buscar: 'P3L02' }, 
           { id: '1QxyVaAmFQw7-2NgiVwhB2Ald9MUzlsff', youtubeId: 'RIcuey5eHgc', buttonId: '1klK7Ye0O9y1tYThMLqnRHQ', title: 'MISSION IMPOSSIBLE GHOST PROTOCOL', subtitle: 'Mision Imposible Protocolo Fantasma (2011)', buscar: 'P3L02' }, 
           { id: '1RFyGV8bkOobc7eSnH3eGOTvNI1ydOmIg', youtubeId: 'ia1chfUsl00', buttonId: '1_kaKMFZ5nh3B_5p1YQE25w', title: 'MISSION IMPOSSIBLE ROGUE NATION', subtitle: 'Misión Imposible Nación Secreta (2015)', buscar: 'P3L02' }, 
           { id: '1WDm5YzGGuQ6bmeabLxvJOOQDnpX8CqWV', youtubeId: 'xhZbbpu-cFE', buttonId: '1MDmH1moFdL2D6Qobel-fag', title: 'MOANA 2', subtitle: 'Moana 2 (2024)', buscar: 'P3L01G' }, 
           { id: '1SCQj2UW0OpiY2pmIFXDZr9UpHradVcWF', youtubeId: 'vq70brIQP40', buttonId: '16tLiJUaA1KfY4AQ-ubLFKQ', title: 'MONSTER', subtitle: 'Monster Asesina En Serie (2003)', buscar: 'P3L01' }, 
           { id: '1PhihTgDIX-JTwIlzaEVS1okiIm6jp-po', youtubeId: 'rACXzbOoHBI', buttonId: '1-s_Y75lIkr106O2y9f5v1w', title: 'MONSTERS INSIDE THE 24 FACES OF BILLY MILLIGAN', subtitle: 'Las 24 Caras De Billy Milligan(2021)', subtitle2: '1 Temporada 4 Episodios', buscar: 'S3R01' }, 
           { id: '1aomOpuEYZko9Nuh89pHVb82v882rEnej', youtubeId: 'WWq6ios-HmI', buttonId: '1hB6W2hndW0Kn0xwklSa7pA', title: 'MONSTERS UNIVERSITY', subtitle: 'Monsters University (2013)', buscar: 'P3L02' }, 
           { id: '1ue4eC3haYqRCqMK1ueZ4XHz5p6KKhBXa', youtubeId: 'rqmHSR0bFU8', buttonId: '1nANcvNzj115F7s1aJKyJpA', title: 'MORGAN', subtitle: 'Morgan (2016)', buscar: 'peroiz#g' }, 
           { id: '1Jktvbu6Mk_dui9QJCGgPXZ5kBYqgp5Ep', youtubeId: 'I1vccr3yWBU', buttonId: '1CMx_HscuBpQstWN3Cg4OkA', title: 'MORTAL KOMBAT LEGENDS SCORPION\’S REVENGE', subtitle: 'Mortal Kombat Leyendas La Venganza De Scorpion (2020)', buscar: 'P3L01' }, 
           { id: '1UpThsk_Akztn4IZG_l7uesKq1BMuIHwa', youtubeId: 'ASw47FiEhes', buttonId: '1ZwfkhiIx9KNeka99_tMMHA', title: 'MR. DEEDS', subtitle: 'La Herencia De Mr. Deeds (2002)', buscar: 'P3L01' }, 
           { id: '1rgvLvr2S1slmBuHRhF3nn-Qnm-bR8ut2', youtubeId: 'rmCAg6RbkTE', buttonId: '1vMuor-YzG_fYMazva2_ypw', title: 'MULAN', subtitle: 'Mulan (1998)', buscar: 'P3L02' }, 
           { id: '198MayE-oL3biusdojq1nF8KMOx-L6Rrj', youtubeId: 'gWf2Cg00kD0', buttonId: '1jp0DAEATlF911QUc8pmqHw', title: 'MULAN 2', subtitle: 'Mulán 2 (2004)', buscar: 'P3L02' }, 
           { id: '1oAW-9oQ-jXgYE4JGOSblbILoEg87VfNx', youtubeId: 'kX5jDxFTTFQ', buttonId: '1J2VHev2TcCvVq7kzZuiduQ', title: 'MUPPETS HAUNTED MANSION', subtitle: 'Los Muppets La Mansión Embrujada (2021)', buscar: 'P3L01' }, 
           { id: '1x-1f6y-bF1voM9V-dxFqyajLySAJaeAK', youtubeId: '5YEVQDr2f3Q', buttonId: '1ejdrilGYoilr96CbA2YaxQ', title: 'MURDER MYSTERY', subtitle: 'Misterio a Bordo (2019)', buscar: 'P3L01' }, 
           { id: '1f8vqJlrdmfzB5ZNdMgcs74XDwHJgVWV1', youtubeId: 'LM2F56uK0fs', buttonId: '1lX6HxrAFXjKnyAdm3zK9ug', title: 'MURDER MYSTERY 2', subtitle: 'Misterio a La Vista (2023)', buscar: 'P3L01' }, 
           { id: '1lIDhVaiPGjiSkF_HEiIt2VQSCq8k-OLz', youtubeId: 'fa8rH44QjCc', buttonId: '1D0Q6p_Egtu-nkQ7kGXu80w', title: 'MY FATHER IS A HERO', subtitle: 'Mi padre es un héroe (1995)*', buscar: 'P3L02' }, 
           { id: '1s4_C7gDL0txIF_316UBjHo0OeKnqRH0O', youtubeId: 'ZOl7iOrD31Q', buttonId: '1fE8bjLR7wsMAxfM3gUZ0oQ', title: 'MY NAME', subtitle: 'Mi Nombre (2021)', subtitle2: '1 Temporada 8 Episodios', buscar: 'S3R01' }, 
           { id: '1Ucw1YhJAVUkSx3pBwo1KkhSMYQ4IZjI_', youtubeId: 'F_z14DEfqfI', buttonId: '1OjNXX-ezWjiGsenCuNXVbA', title: 'MY NAME IS NOBODY', subtitle: 'Mi Nombre Es Ninguno (1973)', buscar: 'BUSCAR' }, 
           { id: '1DH4SXn0c7FBEYBviOQ3wpp-x5gjhOA-4', youtubeId: 'BDzaXh6lXvk', buttonId: '1m61hiuWKl2QaBO_JYVrwmw', title: 'MY NAME IS LOH KIWAN', subtitle: 'Me llamo Loh Kiwan (2024)', buscar: 'P3L02' }, 
           { id: '1fVG7V_Bbszd_NsrjHUhSbd0G0BjYxT3t', youtubeId: '92a7Hj0ijLs', buttonId: '15BbbBqXC7WKlqINtrjsSBQ', title: 'MY NEIGHBOR TOTORO', subtitle: 'Mi Vecino Totoro (1988)', buscar: 'P3L01' }, 
           { id: '1QeDzRD1PuNKMBVsSuc_XKmpegMf9MIFS', youtubeId: 'LIM57Tr9-Dw', buttonId: '1gc6OnG3p_Jq33_T3qeq9fw', title: 'MY SASSY GIRL', subtitle: 'Una Chica Fuera De Serie (2008)', buscar: 'P3L01' }, 
           { id: '1V0s4jIdPC3kH7pyneUnuabrTt-VaI44J', youtubeId: 'jp0Ka7k61go', buttonId: '1EmvSZnGcWYgTl_Ki3lQUyg', title: 'MYTHIC QUEST', subtitle: 'Mythic Quest (2020-22) [Ing T+Esp]', subtitle2: '3 Temporadas 30 Episodios', buscar: 'P3L01G' },

            // ... TODOS los demás elementos de este carrusel
        ]
    }
];