const data_peliculasF= [
     { id: 'PelículasF', data: [
          { id: '18Gf8k_w-sVkjwicyK6LicpArpTTaobqv', youtubeId: '32RAq6JzY-w', buttonId: '1AAZ-bkAMx4jrxqV1TuxsyA', title: 'FAST X', subtitle: 'Rápidos y Furiosos X (2023)', buscar: 'P3L01' }, 
           { id: '18Sj17k3o2JAsEgVcbsOixzfHTAwLMt4r', youtubeId: '8OYHyMa-oF0', buttonId: '1P8NcxGGCZJurRlVq-Kh9Aw', title: 'FATHER OF THE BRIDE', subtitle: 'El Padre De La Novia (1991)', buscar: 'P3L02' }, 
           { id: '18Ttfx0o8kk_Qu5I8l1HEpICgC1vs_UwO', youtubeId: 'BbvnDlu_Zjc', buttonId: '1qeOhl38mhRXSk_JhVxgF-w', title: 'FATHER OF THE BRIDE PART II', subtitle: 'El Padre De La Novia 2 (1995)', buscar: 'P3L02' }, 
           { id: '1jIcwQg6BJn_UXUKAL9jCgUo8IcdJQCpM', youtubeId: 'pzgtTsBf2cQ', buttonId: '1Lg1p1IthsoPM2Iw4oy7_Gg', title: 'FCK VALENTINE\'S DAY', subtitle: 'Fck Valentine\'s Day (2026) [Ing]', buscar: 'peroiz#g' }, 
           { id: '1V8kzQeRlanCi5lp9KxTiHvOSUdzOu7Si', youtubeId: 'jtW0Q9Rh8d4', buttonId: '1QHse4jlBKMVrzAbY4VI31w', title: 'FEAR THE WALKING DEAD', subtitle: 'Fear The Walking Dead (2015-23)', subtitle2: '8 Temporadas 113 Episodios', buscar: 'P3L02G' }, 
           { id: '1jqxjkQQ0zVDrkdJ9gtEZKhrKoKgU_VfO', youtubeId: 'fNkZjTXeaf4', buttonId: '103jTANdfLIx8Clm8MMEgrg', title: 'FEAR THE NIGHT', subtitle: 'Teme a La Noche (2023)', buscar: 'P3L02' }, 
           { id: '18Zk_03wLstZK4uWb_yTy5EAjKCoLVVHO', youtubeId: 's-XHMNDgre8', buttonId: '1Dt4jpEb52aJF4Vgxj60njA', title: 'FERDINAND', subtitle: 'Olé El Viaje De Ferdinand (2017)', buscar: 'P3L01' }, 
           { id: '18dX5t3pxcnr1xQHWGuQdi9Hbutp-eK7l', youtubeId: '4aEJLJmd4b8', buttonId: '1XxQ7BKC1Xygntkq6v5LMQw', title: 'FIFTY SHADES OF GREY', subtitle: 'Cincuenta Sombras De Grey (2015)', buscar: 'P3L01' }, 
           { id: '18ggd785riscGpxgHO54rb0Fz2TOL3Ek3', youtubeId: '0tXaXNCtbZ0', buttonId: '1rq92-U2ew_lUKFsT7DBQbQ', title: 'FIFTY SHADES DARKER', subtitle: 'Cincuenta Sombras Más Oscuras (2017)', buscar: 'P3L01' }, 
           { id: '18m5WV-6iPXzzTJ2gWZmTeHB0d7SO4vgw', youtubeId: 'nJCc5HRPxYA', buttonId: '1z8deG_kpYjslb6Wlb_D7qQ', title: 'FIFTY SHADES FREED', subtitle: 'Cincuenta Sombras Liberadas (2018)', buscar: 'P3L01' }, 
           { id: '1LU3D0V5hzREz5dRvdkWSqYHSNMYbswzu', youtubeId: 'BdJKm16Co6M', buttonId: '1cjQieN6lyy-uvDaucchuHQ', title: 'FIGHT CLUB', subtitle: 'El Club De La Pelea (1999)', buscar: 'P3L01' }, 
           { id: '1FVIneeIf_L0pNkpVrcKXI7pTWw2R80P4', youtubeId: '-LD0SUdJfeU', buttonId: '1GF8m5Ona_AgrkKE5loYMUg', title: 'FIGHTING SPIRIT', subtitle: 'Espiritu De Lucha (2000-14)', subtitle2: '3 Temporadas 127 Episodios 1 OVA', buscar: 'Hajime No Ippo, S3R01' }, {							
								id: '18u5CVi7bjIac-foink8T1o9xWilNATY-', youtubeId: 'J65AGNLI0Es', buttonId: '18izNz7HoKNP9EJRxNXVRsw', title: 'FINAL DESTINATION', subtitle: 'Destino Final (2000)', buscar: 'P3L01' }, 
           { id: '18v3ZC3L4ZoR0cMwf2U3S5cB79JZZkZKQ', youtubeId: 'KEJ-QEHUSAc', buttonId: '1F0rSXlcrYRzFgRaA2xK4vQ', title: 'FINAL DESTINATION 2', subtitle: 'Destino Final 2 (2003)', buscar: 'P3L01' }, 
           { id: '190ix2OjnMKkenOyaTSkNJh1vX4xrpHPc', youtubeId: '1GudpaS3x4U', buttonId: '1X4JvcuL57azJckgcoDPeaA', title: 'FINAL DESTINATION 3', subtitle: 'Destino Final 3 (2006)', buscar: 'P3L01' }, 
           { id: '194cHWgdtPbnuIUjvK5icMNTdRY1LA9Lw', youtubeId: 'TYoK9q8SNzo', buttonId: '1i01vVJCbf_uFrOiGkk89wQ', title: 'FINAL DESTINATION 4', subtitle: 'Destino Final 4 (2009)', buscar: 'P3L01' }, 
           { id: '1924h7XClhuHWx8h30N-N26lynCCBTNzH', youtubeId: 'NM877mmSphc', buttonId: '18MN4xwFbw8Q1hUj113kW5w', title: 'FINAL DESTINATION 5', subtitle: 'Destino Final 5 (2011)', buscar: 'P3L01' }, 
           { id: '19TnSPSE_CsTNaUVI-dwUr1W6gO2Fdykr', youtubeId: '8FudANSsWNQ', buttonId: '1-JqSGTx1SkG6ujEBhCC5dQ', title: 'FINAL DESTINATION: BLOODLINES', subtitle: 'Destino Final: Linajes (2025)', buscar: 'S3R01G' }, 
           { id: '19kis_d0eE5q4yPruOMV4dmeX2dmS3JAm', youtubeId: 'Ec1-3Fjxy0c', buttonId: '1LrfmTA2P5YbXQVmKqL-TUw', title: 'FINAL GIRL', subtitle: 'La Prueba Final (2015)', buscar: 'S3R01' }, 
           { id: '1976LPR6GbRhoUOObhURsffj7tSR5hKYO', youtubeId: 'wZdpNglLbt8', buttonId: '1B_irfLJbZukcFUebvC4w4A', title: 'FINDING NEMO', subtitle: 'Buscando a Nemo (2003)', buscar: 'P3L01' }, 
           { id: '1HQjiSW_Fonh0U3RBvXb1PdfQ9UAZMJ1w', youtubeId: 'oXngES_l_HQ', buttonId: '1J5io-2SPX5LkbtFcUz7MGw', title: 'FIRST BLOOD', subtitle: 'Rambo (1982)', buscar: 'P3L01' }, 
           { id: '19crXydTZA1U6pgV8dj1Wzy7Dkyw5lMkP', youtubeId: 'zfZXiw-lgMs', buttonId: '1fgi7auT51_1veZeCvHklKw', title: 'FIST OF LEGEND', subtitle: 'Furia Sin Limites (1994)', buscar: 'P3L02' }, 
           { id: '19cyd8rLV10adrkQgtEJWNvV_6DE9zXX5', youtubeId: 'XtgCqMZofqM', buttonId: '1YEWAgFDkkXlO3e67IHjbhA', title: 'FIVE FEET APART', subtitle: 'A Dos Metros De Ti (2019)', buscar: 'P3L01' }, 
           { id: '19h0KHEus2FkE7E3az5sDhdW-0jM8YoUE', youtubeId: 'c7t9k9dYenM', buttonId: '1t7mMvYGMu1KKTV2dErlp6g', title: 'FLEE THE LIGHT', subtitle: 'Huye De La Luz (2021)', buscar: 'P3L02' }, 
           { id: '1QYdWgqbWR-GolnIQGpmapvystKPNFxxS', youtubeId: 'OHukIo3qVy4', buttonId: '11XDX1SQfuNZNWFUv8NmlGw', title: 'FLIGHTPLAN', subtitle: 'Plan de vuelo Desaparecida (2005)', buscar: 'P3L01G' }, 
           { id: '1uHBhxCTsPT2HZaiNakg-G9nzwSH9ha7n', youtubeId: 'YQRbTNN-jNE', buttonId: '11o-5V0PkvsJHvPINpDT0Qw', title: 'FLIPPER', subtitle: 'Flipper (1996)', buscar: 'P3L01G' }, 
           { id: '19iBji4OvAGiNp_MoeA0wv1nnVd5dSjeR', youtubeId: 'qxtpXiCP70Q', buttonId: '1qIbPNjgkWa_dTRoiR00e0g', title: 'FLORA & ULYSSES', subtitle: 'Flora y Ulises (2021)', buscar: 'P3L02' }, 
           { id: '19x2LLrlIavgLYSmINqp7YJZZs_y4NniB', youtubeId: '_XkhOSI8BCM', buttonId: '1X0v7aGFl3uJWAXdNpnfmQg', title: 'FORREST GUMP', subtitle: 'Forrest Gump (1994)', buscar: 'P3L01' }, 
           { id: '10Jb8UccbPyLRN12m1sfT258WqBlkLDDd', youtubeId: '7kSpfmAKy6A', buttonId: '1p9L4zTuk-yUeN24yQ0_srw', title: 'FOUNDATION', subtitle: 'Fundación (2021-23)', subtitle2: '2 Temporadas 20 Episodios',buscar: 'P3L01' }, 
           { id: '1OzHrfYgcQ1PhfFLR6Hzx-MxvXdm4ZHhV', youtubeId: '11j2wQFm-tc', buttonId: '1S_jOlKz93Zt9wwhjCJi6Ug', title: 'FRANKENSTEIN', subtitle: 'Frankenstein (2025)', buscar: 'S3R01' }, 
           { id: '1LqGLg9gs7rbpE9dZAdEL7K7hiiqo5hlb', youtubeId: 'BEEVk3jkyFc', buttonId: '1ZsI7hazNO2BANI66Ocd-OQ', title: 'FREAKS', subtitle: 'Fenómenos (2018)', buscar: 'P3L01G' }, 
           { id: '1Z-EI2xUXBtZGFNDIOTfD6wJ3PFi6Rz2t', youtubeId: 'rLsWWX74TeI', buttonId: 'TERABOX', title: 'FREDDY VS. JASON', subtitle: 'Freddy Vs. Jason (2003)', buscar: 'Friday The 13Th, Viernes 13, Pesadilla En La Calle Del Infierno, Pesadilla En La Calle Elm, A Nightmare On Elm Street, La Nueva Pesadilla De West Craven, Wes Craven\'s New Nightmare, Freddy Krueger, S3R3G' }, 
           { id: '1A7JZ4uXlGsXICqO9xRwgYzuXLd5yCc9o', youtubeId: 'BrqWlOzm2Iw', buttonId: '1x_P-k-aerd4-6xJyrUaEIg', title: 'FREELANCE', subtitle: 'El Contratista (2023)', buscar: 'P3L02' }, 
           { id: '1TUNFjWvaDLj0JoqxjZA0-VxWjl1S3dj1', youtubeId: 'aDrOvFtzyPQ', buttonId: '1Pc-Snkld5JTQ9p7WbRkcTw', title: 'FRIDAY THE 13TH', subtitle: 'Viernes 13 (1980)', buscar: 'Jason, P3L01' }, 
           { id: '1iby6pn5Whwh64Q9-THjNq7PVYecSHNVV', youtubeId: 'J-gx4AHReGs', buttonId: '123zu6WXintyVxMYBA3t-9Q', title: 'FRIDAY THE 13TH', subtitle: 'Viernes 13 (2009)', buscar: 'Jason, P3L01' }, 
           { id: '1F0Yp3oUK0ESpXLKMEy_EXkzT07WdPXiM', youtubeId: 'cZ5cMK-3Z_I', buttonId: '1DZ-_0rfCAobgaQNzQgjMxg', title: 'FRIDAY THE 13TH A NEW BEGINNING', subtitle: 'Viernes 13 Un Nuevo Comienzo (1985)', buscar: 'Jason, P3L01' }, 
           { id: '1Z0CgB6dk2HZLxK5jBi7dkhWH_XhpMA5L', youtubeId: '3mNnJuOoI80', buttonId: '1yCGknO3lMjm7YDUTptqKBw', title: 'FRIDAY THE 13TH PART II', subtitle: 'Viernes 13 Parte 2 (1981)', buscar: 'Jason, P3L01' }, 
           { id: '1nSjKx6owf7VgAmGnYgl7jQg-ixMvDOcA', youtubeId: 'SDdBhDJ7wdA', buttonId: '1joNQzUkQsH3_JrV7KqPjNQ', title: 'FRIDAY THE 13TH PART III', subtitle: 'Viernes 13 Parte 3 (1982)', buscar: 'Jason, P3L01' }, 
           { id: '1yQuTExwruDM4MtI-tfr6WQN2ZDA0NtuJ', youtubeId: 'u1vomXv42Sc', buttonId: '1aK4L9oCO0rvyME_cU-PZ2Q', title: 'FRIDAY THE 13TH PART VI JASON LIVES', subtitle: 'Viernes 13 Jason Vive (1986)', buscar: 'P3L01' }, 
           { id: '1EbA89nzOebVS9tFGxDFU9XeyNAoKN3hY', youtubeId: '7AyRUWJriuY', buttonId: '1dPp21_oNrB9uuyac_a4Img', title: 'FRIDAY THE 13TH PART VII THE NEW BLOOD', subtitle: 'Viernes 13 La Nueva Sangre (1988)', buscar: 'Jason, P3L01' }, 
           { id: '1J0qedliVWwWCX_3DLus-hI2H9Yy8uxYn', youtubeId: 'Pvdrit6ij04', buttonId: '1EJ5a9RcQyW51kY6rP-IY4A', title: 'FRIDAY THE 13TH PART VIII JASON TAKES MANHATTAN', subtitle: 'Viernes 13 Jason Toma Manhattan (1989)', buscar: 'P3L01' }, 
           { id: '1ket3cJsdMYAE4qB0t6mY0YWRUtrptyIq', youtubeId: 'OpWpe8REbag', buttonId: '1fL8--kCTq_mj8UYdXheC-A', title: 'FRIDAY THE 13TH THE FINAL CHAPTER', subtitle: 'Viernes 13 El Capitulo Final (1984)', buscar: 'Jason, P3L01' }, 
           { id: '1BS6zKJVio6hBg-dzOj1-R9LizpwrhdTx', youtubeId: 'sLisEEwYZvw', buttonId: '1OZpMH9hk2vF1hXNmCNRKBw', title: 'FRIENDS' , subtitle: 'Friends (1994)', subtitle2: '10 Temporadas 235 Episodios', buscar: 'S3R01' }, 
           { id: '12XaZkmckTTo7GQYSLZnFGmpzQcxjDqzG', youtubeId: 'BclT-pJdoBo', buttonId: '1ev1JxhL9W1rPoUQiLYjc0A', title: 'FRIGHT KREWE', subtitle: 'Fright Krewe (2023)', subtitle2: '1 Temporada 10 Episodios', buscar: 'S3R01' }, 
           { id: '1Y8mlg6xML11JQq4hG7StkgR4hQqhsaUW', youtubeId: 'PMRH0RIEjnc', buttonId: '1Ipu27JlVjVzVp1Vu-XiuKQ', title: 'FRIGHT NIGHT', subtitle: 'Noche Del Espanto (1985)', buscar: 'P3L01G' }, 
           { id: '1wL1IGsror6p9x9hTIzL_M8XAsj3BwXWK', youtubeId: '8-UL3V15E8s', buttonId: '1n17bRse9ghCvG23iJjUxtg', title: 'FROM HELL', subtitle: 'Desde El Infierno (2001)', buscar: 'P3L01G' }, 
           { id: '1nO_ypKGf3z9a67xDZDPv0upk5vVNMhJ4', youtubeId: 'nrcej3bN8QA', buttonId: '1XbxUV8C09aEybUr8pThRWw', title: 'FROM PARIS WITH LOVE', subtitle: 'Desde París Con Amor (2010)', buscar: 'S3R01G' }, 
           { id: '14kEd9AlK9gBCMMfZSbs6Fn7v47OLnzub', youtubeId: 'tBsdM5-ZQbU', buttonId: '1r7LpBnCMg2Q7bZQNAIiCtw', title: 'FROM THE ASHES', subtitle: 'From The Ashes (2024)', buscar: 'P3L02' }, 
           { id: '1pf3LrcD5L72lOLXKIxhuCsadrZ6FsBNZ', youtubeId: 'u4UuOIIR19I', buttonId: '1_JmqJEfrLRORy1gXEYrjdQ', title: 'FROM THE TERRACE', subtitle: 'Desde La Terraza (1960)', buscar: 'P3L01G' }, 
           { id: '1BgNZ74FcBXmWZkbGtfbZvRVvpSwhs8Tq', youtubeId: 'V2RQx6aI0Eg', buttonId: '1kPft-ljA6XVhQ6wkzefWQg', title: 'FRONT OF THE CLASS', subtitle: 'Al frente de la clase (2008)', buscar: 'P3L01' }, 
           { id: '1BidQbH8IYDOerMpK1o4Ot6IKkZdrdA5i', youtubeId: 'SRRRrCNTVJA', buttonId: '1aqZ_lGopmLPj3-gOxHTI1w', title: 'FROZEN', subtitle: 'Frozen Una aventura congelada (2013)', buscar: 'P3L02' }, 
           { id: '1Jl5LrqwDqw7-SMHzqsJ5hSUaz9ep1FDG', youtubeId: 'VqP64AyJNTQ', buttonId: '1Quj_KPm_SEx2fbHx9d9HIg', title: 'FUN SIZE', subtitle: 'El Tamaño Sí Importa (2012) (Esp)', buscar: 'P3L01' }, 
           { id: '1l7ZYYXwF2ixojV9QWrR-bVdnAbkc2w8G', youtubeId: 'TrYJGh2tXhU', buttonId: '1pX4WpvpTOn90fWTWlACA2A', title: 'FUNNY PEOPLE', subtitle: 'Siempre Hay Un Lugar (2009)', buscar: 'P3L01' }, 
           { id: '1sHdX33TrqDUW6FIdSAvY313_eEDn1FLJ', youtubeId: 'B521Z9IXkOw', buttonId: '17Uhob_c9sNM4d71ii1w51A', title: 'FURY', subtitle: 'Corazones De Hierro (2014)', buscar: 'P3L01' }, 
           { id: '1UhksVu2q-66-RTQORfoFWrSKG8iJ6M9U', youtubeId: 'uljtvXrkdbc', buttonId: '1bCcMFIlxAL3qd4jPAav3eg', title: 'FUTURE WORLD', subtitle: 'Guerreros Del Futuro (2018)', buscar: 'P3L01' },
            

            // ... TODOS los demás elementos de este carrusel
        ]
    }
];