function pb(a, b, c, d, e, f, g) {
     x= "https://drive.google.com/thumbnail?id=1";
     y= "https://1024terabox.com/s/1";   
     return {
          image: x + a, youtube: b, terabox: y + c, title: d, subtitle: e, subtitle2: f, search: g
     };
};

const data_peliculasB= [
     { id: "PelículasB", data: [
          pb("oWOd1KfHgQqiYMpWLGoLZ2603x8gQ5hP","5muQK7CuFtY","XY2LNq3x2p3Taj_dfcJatg","BABYLON","","","2022"),
          pb("CRN36aHksyK6YDoJrR6qhBc_6-2PIpF5","OPfPI2m4gWk","jA7bMwHXU20h-VsOGVgftg","BACK AT THE BARNYARD","TEMPORADA 1","","la granja, 2007, the barnyard"),
          pb("8Rsl6bJ80kmVt3Ugf9tcYGMY0SxqJVao","OPfPI2m4gWk","jA7bMwHXU20h-VsOGVgftg","BACK AT THE BARNYARD","TEMPORADA 2","","la granja, 2009"),
          pb("BZq2KiPDHb2Pwl7RBpYrMXYIjv9q1jz2","qvsgGtivCgs","pDkwDT6Wr1ewKPPjKIOzag","BACK TO THE FUTURE","","","volver al futuro, 1985"), 
          pb("O6Z4nm6eXOdgh0QDxCHERVQjk-71seJF","MdENmefJRpw","di3lnBEXH1THPCRU1dsSrw","BACK TO THE FUTURE 2","","","volver al futuro 2, 1989"), 
          pb("bbnHveC5QpEuKpfOKrcmKmQ34zU7QZKY","EYkguxpqsrg","3Qe7eqthqSKqw3LYKRHDWg","BACK TO THE FUTURE 3","","","volver al futuro 3, 1990"), 
          pb("qxlDbxz9WYKNNsLptgsIE48Ckg5VJyPp","OLYENHi4IIc","B5BdWrXG2XW48_Fwy2hJMw","BAD BOYS","","","will smith, dos policias rebeldes, 1995, bad boys, bad boys 2, bad boys 3, bad boys for life, bad boys 4, bad boys ride or die"), 
          pb("FgAIQ_uL2e5pZLPifxrnFD-IFvmpve-O","UTNcOwQ2lRw","zxmNJH3tdo-l-8pO1wb7lw","BAD BOYS 2","","","will smith, dos policias rebeldes 2, 2003, bad boys, bad boys 2, bad boys 3, bad boys for life, bad boys 4, bad boys ride or die"), 
          pb("4ksgXJ-WU83TnwPjKQ1EdYqM7W--2pfM","jKCj3XuPG8M","nZRDyIRjvUBw38IIj3J3qw","BAD BOYS FOR LIFE","","","will smith, dos policias rebeldes 3, bad boys para siempre, 2020, bad boys, bad boys 2, bad boys 3, bad boys for life, bad boys 4, bad boys ride or die"), 
          pb("J5RoHCaQJs44AcrCfXpcxuvfppmu-sLf","mggw7ykX8to","dtluqQw6_aJc87EgVn6Tfw","BAD BOYS RIDE OR DIE","","","will smith, Dos Policias Rebeldes 4, bad boys hasta la muerte, 2024, bad boys, bad boys 2, bad boys 3, bad boys for life, bad boys 4, bad boys ride or die"), 
          pb("lnDntlm3UYn1_o6phCeEtFwPPZoOXpEz","WzWpL6zlA1w","afzelvqd3i3V84o3TWNFkw","BAD CAT","","","gato malo, 2016"), 
          pb("UFIvNfR8OI1Lbnq2U4ECW_7xMU4F-pB4","oDNFCV3oLY0","KUl1WhciTjD8WIyx1d3yqw","BAD HAIR","","","belleza maldita, 2020"), 
          pb("9Z1YG-VVgM_rFybBOzksK3dYXinnie4M","6ldvQ8sv7DU","4NCUvEYLatxOHmZbXN9mPQ","BAD SISTERS","TEMPORADA 1","","hermanas hasta la muerte, 2022"),
          pb("yJS9NBn1JSnO1HeSymesLbolhw6JAeag","6ldvQ8sv7DU","4NCUvEYLatxOHmZbXN9mPQ","BAD SISTERS","TEMPORADA 2","","hermanas hasta la muerte, 2024"), 
          pb("CsFdnEcQWfi0FrhXY9CAhlZZwVVeU1fk","y7wzBVARwaU","oNYinw5xoA8xE3jaVi2kyg","BAD TIMES AT THE EL ROYALE","","","Malos Momentos En El Hotel Royale, 2018"), 
          pb("ES4edl3snoIU6Iv57Ml6Wpr758JvXVLh","hKbo-ZKdSqw","wq4ImC7JmgjmdrFnaX_Cdw","BADLAND HUNTERS","","","cazadores en tierra inhospita, 2024"),
          pb("tFWHvPfkkxNB3tZvU247-ENDaHt_L8Cq","_zvpI4AvMao","_yxAeqKvZKfkNXU4kyCE2A","THE BALKAN LINE","","","heroes de guerra, 2019"), 
          pb("VoA3k8KDMrpSqS7EKY3-9AKtHZs3J1CP","yDGv4GIR7A4","tY65agTGGV9qllJ8iQdmPQ","BAMBI","","","bambi, 1942, peroiz#g"), 
          pb("GBLnna4K0QemZ3iur-Nn6s1KZ5ELxAH5","r1DosMJafGk","wLtbVj_qHwNi-xAOjtdIDQ","BAND OF BROTHERS","TEMPORADA 1","","hermanos de sangre, 2001, band of brothers, the pacific, we stand alone together, band of brothers legacy"),
          pb("S3hSPZ8obyehX3XLVe3gKmu4-G4J9waS","IjLg0X59fMA","TRZ3so-lHJWeynAClYYffw","BAND OF BROTHERS LEGACY","","","Hermanos de sangre legado, 2026, band of brothers, the pacific, we stand alone together, band of brothers legacy, peroiz#g"),
          pb("2pJod3UX1glkFcxRPbRHaIEFGdvBC6cu","x19tdyNa-QI","Rje3J3TQaZH6M71F0p7-Zw","BANG","","","bang, 2025, peroiz#g"), 
          pb("pEq02twX0olw3zsS-yS5LL6TruqmnlBo","nBXsRgy_EtM","Ein6VQyTT02rs7swkB5rUQ","BANK OF DAVE","","","el banco de dave, 2023"),
          pb("1n5xx671HmY0vIGFBFK2094D40_7Yf-7","24u_GSDI3qI","oVfSwvrov2It6-BjXqTI9A","THE BANKER","","","el banquero, 2020"), 
          pb("_ehCvaomQH7r_0Z9Nc3FUdQW8gO4EOAv","HgbTi9wSD-4","TLSyQ-E9FMDiUAF-0Kn13A","BARNYARD","","","la granja, 2006, back at the barnyard"),
          pb("GbLDtQ6JyAfBKaxVBYEe1Q38H2b5Bety","wZXK-3WxK1o","h30T83goJiWlglDblxmaQg","BARRY LYNDON","","","1975"), 
          pb("5EymSrZr_7OUSzV2sP9s1NXJ483I5NQc","WS1s3T-rnFU","JZbhqhJ3qG3YqDJgGbOUdw","BAT-MAN BEYOND","TEMPORADA 1","","batman del futuro, 1999, batman beyond return of the joker, batman vs teenage mutant ninja turtles"),
          pb("uzZi3-FZ2COrrqs4WhK1WNIGLZUCUZSi","WS1s3T-rnFU","JZbhqhJ3qG3YqDJgGbOUdw","BAT-MAN BEYOND","TEMPORADA 2","","batman del futuro, 1999, batman beyond return of the joker, batman vs teenage mutant ninja turtles"),
          pb("Kyby_XWrvP3YSGdWpHO14jmyUNn8-y8v","WS1s3T-rnFU","JZbhqhJ3qG3YqDJgGbOUdw","BAT-MAN BEYOND","TEMPORADA 3","","batman del futuro, 2000, batman beyond return of the joker, batman vs teenage mutant ninja turtles"),
          pb("a3db-S6sRxO02HANYSTY2VAWlbHkgbCl","eChsSqRGy5k","sRheDUK62LyaUfaZXeCtug","BAT-MAN BEYOND RETURN OF THE JOKER","","","batman del futuro el regreso del guason, 2000, batman beyond, batman vs teenage mutant ninja turtles, peroiz#g"), 
          pb("fQdqP68X4YyvG47s8IG3HQ4g5pdvA8cg","J--RQj-Gp8w","fknmhLFBxoD-IkVK4Tm55w","BAT-MAN VS. TENAGE MUTANT NINJA TURTLES","","","batman vs las tortugas ninja, 2019, batman beyond return of the joker, batman vs teenage mutant ninja turtles"), 
          pb("hQjBCMp0zAUiQPee4hqcg6ULLUlmOvPq","yg_cSD2VnE8","Qb6hJn81aeayk0OHIuEgnQ","BATTLE FOR THE PLANET OF THE APES","","","la batalla por el planeta de los simios, 1973, the planet of the apes, battle for the planet of the apes, beneath the planet of the apes"), 
          pb("ZjdGEDCpQm9uOI4LviuSvTdLoteOcsPq","okOsyezoR7s","Dl2f6Ox4a2J4bTdlf_KSOA","BATTLESHIP","","","batalla naval, 2012"), 
          pb("8VFuSGLwYA-JmsZ_NqqpVrqUMNP5UYuL","yUESncu-AH0","d1k6_DMm712mT5EHZopXjg","BEAKMAN\'S WORLD","TEMPORADA 1","","el mundo de beakman, 1992"),
          pb("yFnPv1O0AoxD2-KmAF_87Td9Y6B1p9uB","yUESncu-AH0","d1k6_DMm712mT5EHZopXjg","BEAKMAN\'S WORLD","TEMPORADA 2","","el mundo de beakman, 1993"),
          pb("phiIxHn2D-WlXtRSAyK49jrRPNUq0Hma","yUESncu-AH0","d1k6_DMm712mT5EHZopXjg","BEAKMAN\'S WORLD","TEMPORADA 3","","el mundo de beakman, 1994"),
          pb("4v1k2U_hGHEl-URLX9yOchDpQgbqZpkR","yUESncu-AH0","d1k6_DMm712mT5EHZopXjg","BEAKMAN\'S WORLD","TEMPORADA 4","","el mundo de beakman, 1996"), 
          pb("rtqMXhh8U1Qh5IqgrJLoqkENRtaDEBj6","G-Jnz-ZMtD4","w2Jq6UoUm8wyzOWJFkfGgg","BEASTS OF NO NATION","","","bestias sin patria, 2015"),
          pb("GMEeN2o2aKB_rcdzfE8za4kMiQiXCfGm","Auta2lagtw4","FrR8LT_t7Yg8jY2JgfWqEQ","THE BEATLES GET BACK","TEMPORADA 1","[ INGLES || ESPAÑOL ]","2021"),
          pb("xA9Yx5TlCxAPEPs9dGSmccZpi2qLIKaW","Ccx-MW5Fg6I","8442_xxonqYz9O_kOAK9Bg","BEAUTY AND THE BEAST","","","la bella y la bestia, 2017"), 
          pb("qbbmFxaKbNau863HB0IU4EwOONe17inN","e-6N1NZrQAQ","3qVxGkWRLQ4182FgLBa-zQ","BEDTIME STORIES","","","adam sandler, cuentos que no son cuento 2008"), 
          pb("O9xnotrtMZQx5-7fHiaV9P61l40FOXJy","tfpLEU2YKzc","dY749AQFyUjCTu9dHoGISQ","BEDAZZLED","Al Diablo Con El Diablo","","al diablo con el diablo, 2000"), 
          pb("_VuspLsYwgq08cBF4EQ88Mgrzr5Ucar1","wz5dWmmqwN4","KPazTJe7cIOb-qGpZtCO5w","BEE MOVIE","","","bee movie la historia de una abeja, 2007"), 
          pb("CvT5b-Y40dBf33qNUO2MvuSreScqbxrr","50ic_o5TE1U","IgA87HcdXioHA02h0OrC8g","BEFORE","TEMPORADA 1","","before. 2024"), 
          pb("0uC1JMRP_y8sm4j8jbM_oFehkudPSaDz","VDjH5RDZZEM","72uX4Rye7d-ICbJg-AxWEw","BEHAVING BADLY","","","mal comportamiento, 2014"), 
          pb("kKTLj90bN8lPVevxbRSRhMb8xC9vIbke","mEilNgrpwwM","55fmrx6K_IxQzs4PeizIgg","BEHIND THE LINE ESCAPE TO DUNKIRK","","","detras de la linea escape a dunkerque, 2020"), 
          pb("BuO2pjfaiHI5c3WrVnqSEubFMaTXdfMV","5axOQmsC4yw","vqor4gGPTAIU8IeiYY0lEw","BELLE & SEBASTIAN","","TEMPORADA 1","belle y sebastian, 1981"), 
          pb("-F8-7O80PoWjv9Ina3rvrWsmGW6kW42a","qOSEpi8K-XM","uGJb-2rW5qLKVZn5dGFsgg","BENEATH THE PLANET OF THE APES","","","bajo el planeta de los simios, 1970, the planet of the apes, battle for the planet of the apes, beneath the planet of the apes"),
          pb("lhpeBFhtv2OvwXKaPNMW2aEvphuJgpyX","0FIBVbBcank","aLJBb4szSMU2ZCr47a7jDQ","THE BEST OFFER","","","la mejor oferta, 2013"),
                    pb("ug8s-6PId2raEJGld9FRBuefIqPTrBzH","Oi1Q_UvyvYw","jjglOOIyK8095PX7rcwQCA","BEWITCHED","TEMPORADA 1","","hechizada, 1964"),
                    pb("YULIlFXRUibTQExrc1r06tzHF8kP0OKV","Oi1Q_UvyvYw","jjglOOIyK8095PX7rcwQCA","BEWITCHED","TEMPORADA 2","","hechizada, 1965"),
                    pb("GLUQcEqy8esDlZLP4CNb6Q5viye6S8mV","Oi1Q_UvyvYw","jjglOOIyK8095PX7rcwQCA","BEWITCHED","TEMPORADA 3","","hechizada, 1966"),
                    pb("jhjf_M6tNKSYW811pveIB62RUG3F80Sf","Oi1Q_UvyvYw","jjglOOIyK8095PX7rcwQCA","BEWITCHED","TEMPORADA 4","","hechizada, 1967"),
                    pb("iX3_usP1g2DGgqP8ut1jv8kAGmNI7L0U","Oi1Q_UvyvYw","jjglOOIyK8095PX7rcwQCA","BEWITCHED","TEMPORADA 5","","hechizada, 1968"),
                    pb("RYg7083Tp2qLmWoTEFlzivn5GWUMKW9G","Oi1Q_UvyvYw","jjglOOIyK8095PX7rcwQCA","BEWITCHED","TEMPORADA 6","","hechizada, 1969"),
                    pb("LXLV9L9uvuTdv956-B4r4whrSAR0sp5L","Oi1Q_UvyvYw","jjglOOIyK8095PX7rcwQCA","BEWITCHED","TEMPORADA 7","","hechizada, 1970"),
                    pb("NVQOjYV9FneCZSBDLoFbXoOUBkKfP2ro","Oi1Q_UvyvYw","jjglOOIyK8095PX7rcwQCA","BEWITCHED","TEMPORADA 8","","hechizada, 1971"), 
          pb("Pv8TRBZy5ibp5WWmwJvDx1eWeb8Mzyka","hS05j44UKUU","JHqzkFI3Bfrqxh8jiLFdLQ","BEWITCHED","","","hechizada, 2005"),
          pb("vptODRekTCSWSrMIFtWpJy3QUzAQODac","p34rR9VWkLQ","GEwHnVYcSSwZjo2ix3rHOg","BEYOND BORDERS","","[ ESPAÑOL ]","mas alla de las fronteras 2003"), 
          pb("kN42YfSZtTWw7aRDfNbzEb-1nExv7Q87","hWE6B3g6d5c","z2RS9wa8fDI9OKWeCh3QbQ","BHAKSHAK","","","bhakshak el depredador, 2024"), 
          pb("NJ7-A3GTjRvm4v4Jb-SoDsg9TEeol1s-","yfDlQ-Q12rg","lekhSLUNUuDM1HL5fCpcug","BICENTENNIAL MAN","","","el hombre bicentenario, 1999"),
          pb("FiPoavvU2Ap5jy2RTw7qqaTmGf1LeMu9","U-BeLoEP1gQ","_wgCJCiYRJESEyBnt7s1Ug","THE BIG BAD FOX AND OTHER TALES","","","El Malvado Zorro Feroz y Otros Cuentos, 2017"),
          pb("Wt7sQiB2yHG2nY2Mijue8WxRPOJUqbUn","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 1","","la teoria del big bang"),
          pb("AJndFx667xgzwCF-E7-M_lYg2HqmzN_0","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 2","","la teoria del big bang"),
          pb("S1supKpYzRWI4uQSDbOypHPRp8zFqxBB","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 3","","la teoria del big bang"),
          pb("Kj2oGah1kbWOJxX8_zS8mLXW5KtE_Up3","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 4","","la teoria del big bang"),
          pb("XDMYDEPffosen1_d4T6oo15_-QDyloRt","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 5","","la teoria del big bang"),
          pb("hkBU5PcC1ftv_ygSSfMh2IuaNaJQnzZn","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 6","","la teoria del big bang"),
          pb("2Ea0TGCLy_g-cUhIteN4HjODE8hdUaXn","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 7","","la teoria del big bang"),
          pb("W3j1YssdnDK2abTcawNU5GbGLTolob0L","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 8","","la teoria del big bang"),
          pb("sAVcGj1gfqMkKsKBRM6P6oFnxNvEiIeG","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 9","","la teoria del big bang"),
          pb("wqdl-Sj0wlolr8a93rduXIBpaYI8_JTG","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 10","","la teoria del big bang"),
          pb("DhErTu8ZXPfyRbGVlyD3m4y_3r_zU-_W","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 11","","la teoria del big bang"),
          pb("A3MS14ggGv7mRyd0GzRiMi-4c8-rPV8K","x6H7k3XBlk4","c8a_C_eB4Joe6RY1kpRsug","THE BIG BANG THEORY","TEMPORADA 12","","la teoria del big bang"),
          pb("1XLbkUtzF-HI0fPNrndD-h-7NJcv76bW","jxnccxgybUI","_TFSFWdBJHobtLIoLymUtg","BIG DADDY","","","adam sandler, un papa genial, 1999"), 
          pb("YHtMlocQ9D1AxvoVyRV_5N1EK81vNijR","gZgre_WKDuk","nwjEI7m2yNe0BTMplCOF7Q","BIG HERO 6","","","6 grandes heroes, 2014"), 
          pb("Z0Wu70Kuc_pBMLzlJvS-VYqqZY7B-JGG","3CTwf-bp1zY","uj1kA2C9uhhMxr6shBA2tA","BILLIE EILISH","Glastonbury Festival","[ INGLES || INGLES ]","2022"), 
          pb("hMIuRKe1iNlVySZEM_fvb6RPuoEUUb0l","ErKiCXGrtWI","QowOnkvZ8GHCeEJYET3FcA","BILLY LYNN\'S LONG HALF TIME WALK","","","billy lynn honor y valor, 2016"), 
          pb("bsptEadT-pepekVzwiOky5YxS6kkyh53","WMNX2dP6RNY","0VWDi32pxUR0bBJbRRUjHw","BILLY MADISON","","","adam sandler, tonto pero no tanto, 1995"), 
          pb("49lCZkDPZ0LSYN-3qioYgroWBSIuT46v","iCgYDM5Ngs0","6aN07WxN9iNaPkjD0nElUw","BIRD BOX","","","sandra bullock, a ciegas, 2018"), 
          pb("bUtkmHA2Um6GlUmp7_iHJCCIj5GOFVY4","5wt1FuMWVjs","0pPsfY2lFsnXh1iDY2zEQg","BLACK CAT","TEMPORADA 1","","gato negro, 2005"), 
          pb("VgEzYXejrGeebHG1SOtPjY4ml4ZbZ5Ol","7wnRi3Sclm8","WRfoj9oBqKrw-ksYiu3EGg","BLACK MIRROR BANDERSNATCH","","","2018"), 
          pb("op1sT8HRK0XDToF-k6AIVd8L0YXI1beq","xjDjIWPwcPU","-1tqUVuZwN2M6NN-l9_77Q","BLACK PANTHER","","","2018, black panther, black panther wakanda forever"), 
          pb("QsgJesTg29X-sh5_7LlI8KN59c44wAnI","_Z3QKkl1WyM","x0Hyl2yRkLn_9QC78ale9Q","BLACK PANTHER WAKANDA FOREVER","","","black panther wakanda por siempre, 2022, black panther, black panther wakanda forever"), 
          pb("rioGDTy_mNKIXNtOdZonsaPpA9XAXfnK","8EoCHTK7xPw","KWpk0uLV1_fes8YKZ8amTg","BLACK SABBATH BIRMINGHAM","THE END","BIRMINGHAM INGLATERRA","2017"),
          pb("Wf-TCebcXqwIHT3-h5SXRMUaF1ml3F0S","Cy_znrsuXic","B6ClPRx4Iafj6UoULVBruA","BLACK WIDOW","","","viuda negra, 2021"), 
          pb("84lNHfdd7n2y1TDP8wABlPxXL9ICFvig","BauB7D4yZiE","aQeKhn2BPnno5eB9AD6p6w","BLEACH","","","2018"), 
          pb("tKMcpTM7O0KuFNQ_w-GgiJgaQGWZrQFN","PycUqhQxR1Y","e3fHLa5vlgGKUGnCpRnCDg","BLEEDING STEEL","","","jackie chan, enemigo inmortal, 2017"), 
          pb("2g1z393hShpBWw_1ERr8HpBjy3B0nh3p","V6cKLTmDB-k","72UUgIXYQMc1Yn7cGMffwQ","BLENDED","","","adam sandler, luna de miel en familia, 2014"), 
          pb("5EIWOqGfjuBvhGBXCCjJCUVW6auN0r9x","9wJb3EAmO54","qNxzLqblLUplwa6qJKPFMw","BLINDSPOT","TEMPORADA 1","","punto ciego, 2015"),
          pb("yVSh04hAmBZOvqAgcDd6yeX2RC4r_dRU","9wJb3EAmO54","qNxzLqblLUplwa6qJKPFMw","BLINDSPOT","TEMPORADA 2","","punto ciego, 2016"),
          pb("y6MN0JIL6z97MtkTZOpl2hncBMIjnjpN","9wJb3EAmO54","qNxzLqblLUplwa6qJKPFMw","BLINDSPOT","TEMPORADA 3","","punto ciego, 2017"),
          pb("_BAUyos4A0LlhjNDlVymLOrytWaBHSja","9wJb3EAmO54","qNxzLqblLUplwa6qJKPFMw","BLINDSPOT","TEMPORADA 4","","punto ciego, 2018"),
          pb("m_24EonJ3hl0n0LGG3ICG3woN4Svw6GB","9wJb3EAmO54","qNxzLqblLUplwa6qJKPFMw","BLINDSPOT","TEMPORADA 5","","punto ciego, 2020"), 
          pb("bUR121RnVlXCUpgOkyU_6tz-rItHP3OD","iZwykQK9aZo","WfZz1uevb1OOzgAVGpRvtQ","BLITZ","","","persecucion mortal, 2011"), 
          pb("5E-D5FljOZQf-KvdwuEaO-XrXShvBSDl","TMAlW8Q08hY","wgxCFJtwO5lhpqUm4lTHSA","BLOODY ESCAPE BATS OUT OF HELL","","","2024"),
          pb("FoGqqQZ7qKYNNXVUl_MltcPdh8AzhAcJ","A0UapwJIJn8","7b0P7xpHSM-BopmXPm6b2w","THE BLUE LAGOON","","","la laguna azul, 1980"), 
          pb("WZ3FMXblAq9rO6URDGKEn7ZJ7lrJWmyZ","4JFRdJTszRM","PzRaJuJD-f8L7nlXVLJsYA","THE BODYGUARD","","","el guardaespaldas, 1992"),
          pb("2pVKTMAa6h7521pOQ60Tf4pXWEtvnX5s","6S9c5nnDd_s","h68Ef9zL4eOSsBubJQ2mZQ","BOHEMIAN RHAPSODY","","","Bohemian Rhapsody La Historia De Freddie Mercury, 2018"), 
          pb("Ug4YKFPrx_qIsHu1Vdt17b2hQg5UppAM","BK5WcjsTKWU","Yq6TmvA-fexcUmMTZMrpOQ","BOLT","","","2008"),
          pb("_sv5tL3cOSq8iIoLeyDvpA4y9kKpf5fW","xpZFq0X2bOw","tNy55IMZLwGCNmB4MUkCEg","THE BOOGEYMAN","","","boogeyman tu miedo es real, 2023"),
          pb("KE3cRmdx3R3GR-PhllVylI3_a3Z9-EDG","3KgMW3rowXY","wofdt4ItQMzY4Dw825tchQ","THE BOOKSHOP","","","la libreria, 2017"),
          pb("73ifqJK00OwA-8cpGhT1iqWKL3iUu9bV","aBYS2-1ftOc","nZtPs1O6KTqec8vp5VxZxw","BOONIE BEARS GUARDIAN CODE","","","Boonie Bears El Gran Escape, 2023"),
          pb("bTbdfhQAhHTjPDQC8kBhvyTQcn2LrKJh","dL6_G1z6ymw","3154PV_AyjIqX27PXrnMyg","BORAT CULTURAL LEARNINGS OF AMERICA FOR MAKE BENEFIT GLORIOUS NATION OF KAZAKHSTAN","","","Borat El Segundo Mejor Reportero Del Glorioso País Kazajistán Viaja a América, 2006"), 
          pb("OK60ktim-mtOkzJi98ludD5YACK2Q0eP","b4V4LjpYn38","RZKWq5D1ZO1f_RGE7dVcmg","BORN ON THE FOURTH OF JULY","","","Nacido El Cuatro De Julio, 1994"), 
          pb("jRDFxQwX--uhv_6B0ysJvWSdxoFBXT1K","f01m6yqSQ-I","RZKWq5D1ZO1f_RGE7dVcmg","BOSCO","","","2020"),
          pb("Y4oX6j892dHkEHmOhGtt4nXMVyev4S90","nPkr9HmglG0","40z1jNCvfR2rs3JoYHaH8w","THE BOY WHO HARNESSED THE WIND","","","El Niño Que Domó El Viento, 2019"), 
          pb("SLCkjgUG_gQwgfKSBi5t7zufbk5KtKZp","qKVhDbe9VOo","OJDfl5-d_hmbOSJtjTfU5A","THE BREAKER UPPERERS","","","las separa parejas, 2018"),
          pb("Sr4WgojD1w0fn-45RmMSeOVIaqeVqv7g","RGBiwDguDY4","-bOHAMqdA_uWW_2pX8_tNg","BRIDE OF CHUCKY","","","la novia de chucky, 1998, chucky, bride of chucky"), 
          pb("2kVJAXvxqTR7IxLlu8qRzgur-5wVRmGo","0K3vUvjXhHU","gXBBCF7JqsOW3B4dd7utRA","BROTHER\'S KEEPER","","","mi mejor amigo, 2021"),
          pb("V205KwD_wy076P1D7fG93moaRukMdGBB","BvIj2H1ne0k","6EZS08SD0YM33GJvyfreRw","BROTHERS","","","hermanos, 2009"),
          pb("gr-WZ0Ns2rHCX5iX2Bt8KorfyQ2l2CSC","nm2aZz45pGE","rcemm5XrtWYERbZoa5TUXA","THE BROTHERHOOD OF WAR","","","la hermandad de la guerra, 2004"),
          pb("hC7wktGdZoLUY1VPMNVV8S7veRvcvzrC","fe-luzrqWSk","dZu15LVCKV91DVmk0MLeXA","BRUCE ALMIGHTY","","","jim carrey, todo poderoso, 2003"), 
          pb("CdidKQV0pm4COZ52ugOCtpI4E-B9MmoD","V-daIHTY4NQ","MIeVe_JmaUsZRrX-M3Y8lw","BUFFY THE VAMPIRE SLAYER","","","buffy la caza vampiros, 1992"), 
          pb("NDKX--8JWH4Ci_6xY7BD4KvTs1XKXJvz","5PAbRpzoEX8","5kTrDBlIsynYR1o57qsiDw","BURST ANGEL","TEMPORADA 1","","2004"),
          pb("-IYr8RjXOqBmahGXpgIc1bOTvkfmYCR4","5PAbRpzoEX8","5kTrDBlIsynYR1o57qsiDw","BURST ANGEL","OVA (2007)'","","2007"), 
          pb("iYIDeIz0IegU1xVeNX3fIvWtiyW_qKIL","yJEOJbSuOvI","pT9yqdUwQ1shGbrnP37DeQ","BUTCHER\'S CROSSING","El Cazador De Búfalos","","nicolas cage, el cazador de bufalos, 2022"),
            
     ]}
];